docs: add instructions for protos contribution
TRI-ML/dgp pull request #103
Opened 2022-08-01 11:12 UTC by nehalmamgain

Clarify an important workflow in `CONTRIBUTING.md` to avoid users adding compiled protos through their own workflows.
Example: related [PR](https://github.com/TRI-ML/dgp/pull/102) with above issue.

2022-08-01 11:22 UTC, nehalmamgain commented
How do I run the linter locally before committing this doc change?
Is there a doc on the repo I can refer for that?

2022-08-02 01:43 UTC, tk-woven requested changes
Thanks for this! I poked around but did not find docs for any single linting entrypoint. Probably a feature we could add for developer convenience.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/103#-:-N8RD3epE2wqobZA5Z23:bapsiww)* status: all files reviewed, 1 unresolved discussion (waiting on @nehalmamgain)

___
*[`docs/CONTRIBUTING.md` line 81 at r1](https://reviewable.io/reviews/tri-ml/dgp/103#-N8RCS7r4y-0OwKz71lH:-N8RCS7r4y-0OwKz71lI:b-6qcddj) ([raw file](https://github.com/tri-ml/dgp/blob/92e22a885996b7e1c6d4dd2a3f648ee1699e0ac4/docs/CONTRIBUTING.md#L81)):*
> ```Markdown
> **NOTE:** Any [proto schema](../dgp/proto) changes must be seperated from code changes into an independent commit and PR.
> 
> Also, please ensure to commit the compiled protos to the aformentioned PR by first running `make build-proto`. 
> ```

Thanks! Can you please make this part of the `**NOTE:**` paragraph? Also, let's reword a little to suggest that we need to run `make build-proto` and then include the artifacts it produces in the commit and PR.


<!-- Sent from Reviewable.io -->

2022-08-02 05:12 UTC, nehalmamgain commented
Thanks Tyler, I will push your requested changes later today.

2022-08-03 04:21 UTC, tk-woven approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nehalmamgain)



<!-- Sent from Reviewable.io -->

2022-08-03 04:21 UTC, merged