fix: explicitly load docparams pylint plugin in .pylintrc
TRI-ML/dgp pull request #109
Opened 2022-08-04 00:06 UTC by tk-woven

# Description

This is toward unblocking #101 which is stuck on a pylint configuration issue. We provide some configuration in `.pylintrc` that seems to expect the `check_docs` plugin, but the new plugin is `docparams`. We therefore explicitly load the `docparams` plugin when running pylint.

# Reproduction

Before this change, run

```
pylint setup.py
```

in the root of the repo, and you'll see

```
root@hostname:/home/dgp# pylint setup.py
************* Module /home/dgp/.pylintrc
.pylintrc:1: [E0015(unrecognized-option), ] Unrecognized option found: accept-no-param-doc, accept-no-return-doc, accept-no-yields-doc
```

After this change, the above example runs without errors.

2022-08-04 02:53 UTC, kuanleetri requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/109)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisochoatri and @tk-woven)

___
*[`.pylintrc` line 3 at r1](https://reviewable.io/reviews/tri-ml/dgp/109#-N8alPU57AQu2wBKf7GR:-N8alPU57AQu2wBKf7GS:b-e91pi4) ([raw file](https://github.com/tri-ml/dgp/blob/26d57cfc1a4f36c48a486f1cce9bc0d32943bc15/.pylintrc#L3)):*
> ```INI
> # Copyright 2019-2020 Toyota Research Institute.  All rights reserved.
> [MAIN]
> load-plugins=pylint.extensions.docparams
> ```

Can we involve all the criteria under [MASTER]?


<!-- Sent from Reviewable.io -->

2022-08-04 03:10 UTC, tk-woven reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/109)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisochoatri and @kuanleetri)

___
*[`.pylintrc` line 3 at r1](https://reviewable.io/reviews/tri-ml/dgp/109#-N8alPU57AQu2wBKf7GR:-N8ap5KF7vN9zRC3WCrv:b-azfi9l) ([raw file](https://github.com/tri-ml/dgp/blob/26d57cfc1a4f36c48a486f1cce9bc0d32943bc15/.pylintrc#L3)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

Can we involve all the criteria under [MASTER]?
</blockquote></details>

Unfortunately I don't think we can. The [pylint docs](https://pylint.pycqa.org/en/latest/user_guide/checkers/extensions.html#optional-checkers) ask us to use `MAIN`. I just tried putting this in `MASTER` locally, but then the unrecognized-option error is raised again.


<!-- Sent from Reviewable.io -->

2022-08-04 03:42 UTC, wadimkehl approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/109)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisochoatri and @kuanleetri)

___
*[`.pylintrc` line 3 at r1](https://reviewable.io/reviews/tri-ml/dgp/109#-N8alPU57AQu2wBKf7GR:-N8awaRy3-vUsW_lo-uy:bss2s5x) ([raw file](https://github.com/tri-ml/dgp/blob/26d57cfc1a4f36c48a486f1cce9bc0d32943bc15/.pylintrc#L3)):*
> Can we involve all the criteria under [MASTER]?
SGTM


<!-- Sent from Reviewable.io -->

2022-08-04 22:59 UTC, tk-woven reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/109)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisochoatri and @kuanleetri)

___
*[`.pylintrc` line 3 at r1](https://reviewable.io/reviews/tri-ml/dgp/109#-N8alPU57AQu2wBKf7GR:-N8f4EG493fFvNYhq4d-:bhr4brd) ([raw file](https://github.com/tri-ml/dgp/blob/26d57cfc1a4f36c48a486f1cce9bc0d32943bc15/.pylintrc#L3)):*
<details><summary><i>Previously, wadimkehl (Wadim Kehl) wrote…</i></summary><blockquote>

> Can we involve all the criteria under [MASTER]?
SGTM
</blockquote></details>

After discussing review criteria with Kuan in a Slack DM, I'll dismiss this comment and proceed to merge to unblock the MRs stuck on this. As noted, I tested the recommendation for `MASTER` and had no luck unfortunately, but following the instruction of the docs I linked to did the trick.


<!-- Sent from Reviewable.io -->

2022-08-04 23:01 UTC, merged

2022-08-05 00:17 UTC, nehalmamgain commented
Thanks so much Tyler, much appreciated!