fix: supported extensions in compute_image_statistics method
TRI-ML/dgp pull request #130
Opened 2022-10-04 11:42 UTC by yuta-tsuzuki-woven

Some ML teams are handling image data with uppercase extensions such as `.JPG`, `.PNG`.
If there are no negative effects, I would like to support such uppercase extensions in `compute_image_statistics` method.

2022-10-04 11:43 UTC, yuta-tsuzuki-woven reviewed
+@kuanleetri +@chrisochoatri please review it

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/130#-:-NDXnYzw1UN1w_UEpsnW:bdwm0yu)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @chrisochoatri and @kuanleetri)



<!-- Sent from Reviewable.io -->

2022-10-04 16:25 UTC, chrisochoatri requested changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/130)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kuanleetri and @yuta-tsuzuki-woven)

___
*[`dgp/utils/dataset_conversion.py` line 75 at r1](https://reviewable.io/reviews/tri-ml/dgp/130#-NDYnlbbBDZNQVUuNVaV:-NDYnlbbBDZNQVUuNVaW:b-sk665h) ([raw file](https://github.com/tri-ml/dgp/blob/ffd84d783e831ba2c53670a6ab580bb104967287/dgp/utils/dataset_conversion.py#L75)):*
> ```Python
> 
>     valid_extensions = (
>         ".jpg",
> ```

nit: do we need .jpeg also?



_Code quote:_
```Python
.jpg"
```
___
*[`dgp/utils/dataset_conversion.py` line 86 at r1](https://reviewable.io/reviews/tri-ml/dgp/130#-NDYnvLK-YRKwrH5OrRq:-NDYnvLK-YRKwrH5OrRr:b19vz2g) ([raw file](https://github.com/tri-ml/dgp/blob/ffd84d783e831ba2c53670a6ab580bb104967287/dgp/utils/dataset_conversion.py#L86)):*
> ```Python
>         ".TIFF",
>     )
>     image_list = list(filter(lambda x: x.endswith(valid_extensions), image_list))
> ```

just a question, would it make sense to do something like x.lower().endswith and just keep the lower case extensions?



_Code quote:_
```Python
    image_list = list(filter(lambda x: x.endswith(valid_extensions), image_list))
```


<!-- Sent from Reviewable.io -->

2022-10-05 00:50 UTC, yuta-tsuzuki-woven reviewed
@chrisochoatri please next round

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/130#-:-ND_bluG-jNPp2Hz6ZHT:boi5w0o)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @kuanleetri)

___
*[`dgp/utils/dataset_conversion.py` line 75 at r1](https://reviewable.io/reviews/tri-ml/dgp/130#-NDYnlbbBDZNQVUuNVaV:-ND_bMM0DNyVXb3wpsE5:bsypmfm) ([raw file](https://github.com/tri-ml/dgp/blob/ffd84d783e831ba2c53670a6ab580bb104967287/dgp/utils/dataset_conversion.py#L75)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: do we need .jpeg also?
</blockquote></details>

Thank you! It looks nice.
I added `.jpeg`.
___
*[`dgp/utils/dataset_conversion.py` line 86 at r1](https://reviewable.io/reviews/tri-ml/dgp/130#-NDYnvLK-YRKwrH5OrRq:-ND_bVuY3NmE4fiL1i19:b-rbkgmx) ([raw file](https://github.com/tri-ml/dgp/blob/ffd84d783e831ba2c53670a6ab580bb104967287/dgp/utils/dataset_conversion.py#L86)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

just a question, would it make sense to do something like x.lower().endswith and just keep the lower case extensions?
</blockquote></details>

Thank you for your advice. It makes sense.
I added `.lower()` here and remove uppercase extensions from the list.


<!-- Sent from Reviewable.io -->

2022-10-05 01:45 UTC, chrisochoatri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/130#-:-ND_oQGk3R-q0ts54w_W:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kuanleetri)



<!-- Sent from Reviewable.io -->

2022-10-05 01:47 UTC, merged