Dgp2wicker update3
TRI-ML/dgp pull request #142
Opened 2023-01-06 08:25 UTC by chrisochoatri

- Adds support in dgp2wicker for key_point_2d, key_line_2d, key_point_3d, and key_line_3d
- Adds key_point_2d and key_line_3d support to SynchronizedScene 
- Fixes bug in dgp2wicker semantic segmentation 2d
- Removes duplicate code for most dgp2wicker serializers by switching open_pbobject to overloaded version parse_pbobject which can operate on bytes
- Skips unknown annotation types sometimes found in PD datasets in base_dataset
- Adds support for ontology V1 in dgp2wicker
- Fixes bug in dgp2wicker radar_point_cloud 2d annotation type handling

2023-01-06 09:23 UTC, chrisochoatri reviewed
+@kuanleetri feature review
fyi @akira-wakatsuki-woven 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/142#-:-NL5O65a2GIVej-ZiiUE:bhe29zj)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @kuanleetri)



<!-- Sent from Reviewable.io -->

2023-01-09 02:38 UTC, kuanleetri requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/142)* status: all files reviewed, 4 unresolved discussions (waiting on @chrisochoatri)

___
*[`dgp/annotations/semantic_segmentation_2d_annotation.py` line 71 at r1](https://reviewable.io/reviews/tri-ml/dgp/142#-NLJMYNjCZVODyTCE1Hn:-NLJMYNjCZVODyTCE1Ho:b-7jbqan) ([raw file](https://github.com/tri-ml/dgp/blob/a4b97a39af8364b7c9370d712f4de730eb3cd7f5/dgp/annotations/semantic_segmentation_2d_annotation.py#L71)):*
> ```Python
>     def _convert_contiguous_to_class(self):
>         """Helper function to run pre processing prior to saving
>         
> ```

space
___
*[`dgp/contribs/dgp2wicker/dgp2wicker/serializers.py` line 200 at r1](https://reviewable.io/reviews/tri-ml/dgp/142#-NLJNnO75M2oCTm1MRNz:-NLJNnO8CE_xvSYxUjW9:b-qxo0pz) ([raw file](https://github.com/tri-ml/dgp/blob/a4b97a39af8364b7c9370d712f4de730eb3cd7f5/dgp/contribs/dgp2wicker/dgp2wicker/serializers.py#L200)):*
> ```Python
>         return BytesField(name, required=False, is_heavy_pointer=True)
> 
>     def serialize(self, annotation: Optional[KeyPoint2DAnnotationList]) -> bytes:
> ```

I'm confused here...3D becomes 2D? what about the original 3D bbox?
___
*[`dgp/utils/protobuf.py` line 50 at r1](https://reviewable.io/reviews/tri-ml/dgp/142#-NLJN1khA5ToTKNF_V3e:-NLJN1khA5ToTKNF_V3f:b-7jbqan) ([raw file](https://github.com/tri-ml/dgp/blob/a4b97a39af8364b7c9370d712f4de730eb3cd7f5/dgp/utils/protobuf.py#L50)):*
> ```Python
> def parse_pbobject(source, pb_class):
>     """Like open_pboject but source can be a path or a bytestring
>     
> ```

space
___
*[`dgp/utils/protobuf.py` line 55 at r1](https://reviewable.io/reviews/tri-ml/dgp/142#-NLJN2_DEFnLIfWnKOim:-NLJN2_DEFnLIfWnKOin:b-7jbqan) ([raw file](https://github.com/tri-ml/dgp/blob/a4b97a39af8364b7c9370d712f4de730eb3cd7f5/dgp/utils/protobuf.py#L55)):*
> ```Python
>     source: str or bytes
>         Local JSON file path, remote s3 path to object, or bytestring of serialized object
>     
> ```

space


<!-- Sent from Reviewable.io -->

2023-01-09 05:42 UTC, chrisochoatri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/142)* status: all files reviewed, 4 unresolved discussions (waiting on @kuanleetri)

___
*[`dgp/contribs/dgp2wicker/dgp2wicker/serializers.py` line 200 at r1](https://reviewable.io/reviews/tri-ml/dgp/142#-NLJNnO75M2oCTm1MRNz:-NLK23e6-_LqWH_hZiNk:bd2nta4) ([raw file](https://github.com/tri-ml/dgp/blob/a4b97a39af8364b7c9370d712f4de730eb3cd7f5/dgp/contribs/dgp2wicker/dgp2wicker/serializers.py#L200)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

I'm confused here...3D becomes 2D? what about the original 3D bbox?
</blockquote></details>

ooops, typo! nice catch


<!-- Sent from Reviewable.io -->

2023-01-09 06:22 UTC, chrisochoatri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/142)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @kuanleetri)

___
*[`dgp/annotations/semantic_segmentation_2d_annotation.py` line 71 at r1](https://reviewable.io/reviews/tri-ml/dgp/142#-NLJMYNjCZVODyTCE1Hn:-NLKBBau83yYMkv2sx3W:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/a4b97a39af8364b7c9370d712f4de730eb3cd7f5/dgp/annotations/semantic_segmentation_2d_annotation.py#L71)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

space
</blockquote></details>

Done.
___
*[`dgp/contribs/dgp2wicker/dgp2wicker/serializers.py` line 200 at r1](https://reviewable.io/reviews/tri-ml/dgp/142#-NLJNnO75M2oCTm1MRNz:-NLKBDFBBqcF9kCqY7QF:bb6un1j) ([raw file](https://github.com/tri-ml/dgp/blob/a4b97a39af8364b7c9370d712f4de730eb3cd7f5/dgp/contribs/dgp2wicker/dgp2wicker/serializers.py#L200)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

ooops, typo! nice catch
</blockquote></details>

Done
___
*[`dgp/utils/protobuf.py` line 50 at r1](https://reviewable.io/reviews/tri-ml/dgp/142#-NLJN1khA5ToTKNF_V3e:-NLKBK5uDGZzMm1wUkJD:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/a4b97a39af8364b7c9370d712f4de730eb3cd7f5/dgp/utils/protobuf.py#L50)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

space
</blockquote></details>

Done.
___
*[`dgp/utils/protobuf.py` line 55 at r1](https://reviewable.io/reviews/tri-ml/dgp/142#-NLJN2_DEFnLIfWnKOim:-NLKBKag3tqv79gtYJqF:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/a4b97a39af8364b7c9370d712f4de730eb3cd7f5/dgp/utils/protobuf.py#L55)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-09 21:31 UTC, akira-wakatsuki-woven reviewed
+@yuta-tsuzuki-woven Can you take a look?
cc @chunleng-woven 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/142#-:-NLNRUvh8bxRwb7gA49W:bcq9nie)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @kuanleetri and @yuta-tsuzuki-woven)



<!-- Sent from Reviewable.io -->

2023-01-10 01:30 UTC, yuta-tsuzuki-woven submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with minor comments

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/142#-:-NLOIAvr8vBm3kiOaVq5:b-ij5eeu)* status: all files reviewed, 6 unresolved discussions (waiting on @chrisochoatri and @kuanleetri)

___
*[`dgp/annotations/semantic_segmentation_2d_annotation.py` line 57 at r2](https://reviewable.io/reviews/tri-ml/dgp/142#-NLOFejLBmZTRHegXoUF:-NLOFejLBmZTRHegXoUG:b-i7v1lj) ([raw file](https://github.com/tri-ml/dgp/blob/66cdd1efc33683a26537b1567533b491ee64b8ff/dgp/annotations/semantic_segmentation_2d_annotation.py#L57)):*
> ```Python
>             segmentation_image = cv2.imdecode(np.frombuffer(raw_bytes.getbuffer(), np.uint8), cv2.IMREAD_UNCHANGED)
>         else:
>             # segmentation_image = np.array(Image.open(annotation_file), dtype=np.uint8)
> ```

nit, is this an unnecessary code?
___
*[`dgp/contribs/dgp2wicker/dgp2wicker/serializers.py` line 205 at r2](https://reviewable.io/reviews/tri-ml/dgp/142#-NLOGIZl1HZYGBQyMQ9m:-NLOGIZl1HZYGBQyMQ9n:b-4k98k5) ([raw file](https://github.com/tri-ml/dgp/blob/66cdd1efc33683a26537b1567533b491ee64b8ff/dgp/contribs/dgp2wicker/dgp2wicker/serializers.py#L205)):*
> ```Python
>         return annotation.to_proto().SerializeToString()
> 
>     def unserialize(self, raw: bytes) -> KeyPoint2DAnnotationList:
> ```

Nit, `KeyPoint2DAnnotationList` -> `BoundingBox3DAnnotationList`?


<!-- Sent from Reviewable.io -->

2023-01-10 08:43 UTC, chrisochoatri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/142)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @kuanleetri and @yuta-tsuzuki-woven)

___
*[`dgp/annotations/semantic_segmentation_2d_annotation.py` line 57 at r2](https://reviewable.io/reviews/tri-ml/dgp/142#-NLOFejLBmZTRHegXoUF:-NLPq9BmExcAjXGiIeRT:b-78f1h4) ([raw file](https://github.com/tri-ml/dgp/blob/66cdd1efc33683a26537b1567533b491ee64b8ff/dgp/annotations/semantic_segmentation_2d_annotation.py#L57)):*
<details><summary><i>Previously, yuta-tsuzuki-woven wrote…</i></summary><blockquote>

nit, is this an unnecessary code?
</blockquote></details>

yeah it was in the original code so I had left it. But on second thought, removed it. Thanks!
___
*[`dgp/contribs/dgp2wicker/dgp2wicker/serializers.py` line 205 at r2](https://reviewable.io/reviews/tri-ml/dgp/142#-NLOGIZl1HZYGBQyMQ9m:-NLPpbKs22lbzhTbqacs:b-zcrwn3) ([raw file](https://github.com/tri-ml/dgp/blob/66cdd1efc33683a26537b1567533b491ee64b8ff/dgp/contribs/dgp2wicker/dgp2wicker/serializers.py#L205)):*
<details><summary><i>Previously, yuta-tsuzuki-woven wrote…</i></summary><blockquote>

Nit, `KeyPoint2DAnnotationList` -> `BoundingBox3DAnnotationList`?
</blockquote></details>

🤦 fixed


<!-- Sent from Reviewable.io -->

2023-01-12 01:00 UTC, kuanleetri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/142#-:-NLYU_A83x3cEFna6syF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yuta-tsuzuki-woven)



<!-- Sent from Reviewable.io -->

2023-01-12 01:02 UTC, merged