schema: add agent schema
TRI-ML/dgp pull request #63
Opened 2021-11-18 22:40 UTC by visakii-work

Read ME needs updating

2021-11-29 21:10 UTC, ChaoFang-TRI approved these changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2021-11-29 21:10 UTC, ChaoFang-TRI approved these changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2021-11-30 22:17 UTC, quincy-kh-chen requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 26 unresolved discussions (waiting on @visakii-work)

___
*[dgp/proto/agent.proto, line 12 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmpxgo4eTDUfVdZaps:-Mpmpxgo4eTDUfVdZapt:bu41qdv) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L12)):*
> ```protobuf
> import "google/protobuf/timestamp.proto";
> ```

I would reorder this file by arranging the data containers in a bottom-up way i.e. from `AgentSnapshot2D/3D` to `AgentSnapshot` to `AgentSlice` to `AgentGroup` or vice versa (top-down). IMO it's more understandable. Currently it's unordered.
___
*[dgp/proto/agent.proto, line 13 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmnLiz10c97ktGsrO7:-MpmnLiz10c97ktGsrO8:b-n4r5oo) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L13)):*
> ```
> robot session
> ```
What's the DGP equivalent to `robot session`? Is this scene or sample or just all agents in a time interval. Let's elaborate it in comments.
___
*[dgp/proto/agent.proto, line 15 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmoWII2wDbRTibipi-:-MpmoWII2wDbRTibipi0:bs53vwb) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L15)):*
> ```
> scene
> ```
`Scene.`
___
*[dgp/proto/agent.proto, line 20 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmonKsAbCTgVQHmdKQ:-MpmonKsAbCTgVQHmdKR:b-yzvtjl) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L20)):*
> ```protobuf
>   // the agents.
>   //
>   // For group without without unique names, generate a sha1 hash of
> ```

rm duplicated `without`
`For group without without unique names` -> `For the group without a unique names`?
___
*[dgp/proto/agent.proto, line 24 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmp5Nw23PX8INn0hKO:-Mpmp5Nw23PX8INn0hKP:b-mlxodd) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L24)):*
> ```protobuf
>   string name = 1;
> 
>   // Optional, short description of the group (~200 characters)
> ```

Following the convention, please end a sentence with a period.
___
*[dgp/proto/agent.proto, line 41 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmpIakA8ecKoaqJ_eN:-MpmpIakA8ecKoaqJ_eO:b-ef1i5c) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L41)):*
> ```protobuf
>   map<string, google.protobuf.Any> metadata = 6;
> 
>   // Date and timestamp of agent group creation
> ```

period

BTW why do we need `creation_date` for `AgentGroup`?
___
*[dgp/proto/agent.proto, line 66 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmqv5HAs_xbamO5IhG:-Mpmqv5HAs_xbamO5IhH:b-eys1ns) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L66)):*
> ```protobuf
>   // Copy from sample ID to ensure one-one match between a agent slice and sample
>   // in a scene.
>   DatumId slice_id = 3;
> ```

BTW is this the double link being used to trace back to which `AgentsSlice` includes this `AgentSnapshot`?
___
*[dgp/proto/agent.proto, line 75 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmr7w7821WrKKBhXkI:-Mpmr7w8CAbFso4-_8_u:b-2rqikh) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L75)):*
> ```protobuf
> message AgentsSlice {
>   // Unique slice identifier (See dgp.idenfiers.proto)
>   // Copy from sample ID to ensure one-one match between a agent slice and sample
> ```

Let's elaborate what's `sample ID`. Referring to https://github.com/TRI-ML/dgp/blob/master/dgp/proto/sample.proto#L84?
___
*[dgp/proto/agent.proto, line 91 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmroHIAbPTjz-rGz8o:-MpmroHIAbPTjz-rGz8p:b1mhim8) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L91)):*
> ```protobuf
> }
> 
> message AgentTrack {
> ```

Add some comments to explain what's `AgentTrack`
___
*[dgp/proto/agent.proto, line 93 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmrgsv5Yl2qOOAhaiK:-Mpmrgsv5Yl2qOOAhaiL:b-6pemic) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L93)):*
> ```protobuf
> message AgentTrack {
>   // Class identifier (should be in [0, num_classes - 1])
>   uint32 class_id = 1;
> ```

add empty lines between the fields below to follow the convention in this file.
___
*[dgp/proto/agent.proto, line 123 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpms1Pq4n4yqRc8Z-2G:-Mpms1Pq4n4yqRc8Z-2H:bi483if) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L123)):*
> ```
>   bool iscrowd = 4;
> ```
Add a comment and an empty line in between
___
*[dgp/proto/agent.proto, line 128 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsCRk0suPhtfqElkA:-MpmsCRk0suPhtfqElkB:b-g3d5io) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L128)):*
> ```protobuf
>   uint32 instance_id = 5;
> 
>   // list of feature values. This is used to stored `agent` states. The schema
> ```

/stored/store/
___
*[dgp/proto/agent.proto, line 128 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsGHH4OHIvL0fx-mv:-MpmsGHH4OHIvL0fx-mw:b1twdqj) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L128)):*
> ```
> list
> ```
/list/List/ 
Let's start a sentence with uppercase
___
*[dgp/proto/agent.proto, line 128 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsYVr5FJuHFSWxYAO:-MpmsYVr5FJuHFSWxYAP:bgwflh6) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L128)):*
> ```
> The schema
> ```
Could you elaborate what does `schema` refer to?
___
*[dgp/proto/agent.proto, line 129 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsPZyASLZMkr7X9WW:-MpmsPZyASLZMkr7X9WX:b-lsg4p0) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L129)):*
> ```
> i.e.,
> ```
/,parked car/ parked car/
___
*[dgp/proto/agent.proto, line 152 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmuzvsDNo-joVMK-2P:-MpmuzvtCVGgBE4--OK7:bt08eq2) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L152)):*
> ```protobuf
> 
>   // The type of feature ontology defined in FeatureType in features.proto.
>   int32 feature_type = 5;
> ```

Isn't `uint32` enough?
___
*[dgp/proto/annotations.proto, line 1 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmsl296iuREylin5mZ:-Mpmsl296iuREylin5m_:bpu7qsc) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L1)):*
> ```protobuf
> // Copyright 2021 Toyota Research Institute.  All rights reserved.
> ```

 keep `2019-2021`
___
*[dgp/proto/annotations.proto, line 132 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmsttf0r_RD28_lUCx:-Mpmsttf0r_RD28_lUCy:b7rm2vt) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L132)):*
> ```
> Frame index
> ```
Sample index?
___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-MpmtMa59aqzxQ6uahMN:b-iiiqrg) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
> ```protobuf
> 
>   // Frame index in the scene
>   int32 sample_idx = 7;
> ```

This field looks unnecessary to me. Since this is a base object and we should avoid storing top-level metadata (SceneData [...]

2021-12-01 23:45 UTC, ChaoFang-TRI submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 26 unresolved discussions (waiting on @quincy-kh-chen and @visakii-work)

___
*[dgp/proto/agent.proto, line 91 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmroHIAbPTjz-rGz8o:-MpsN50tAoa7K_3nlaQy:b-m14vbo) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L91)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Add some comments to explain what's `AgentTrack`
</blockquote></details>

AgentTrack is a track of a single agent in the scene.
___
*[dgp/proto/agent.proto, line 123 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpms1Pq4n4yqRc8Z-2G:-MpsMzJI8BF_kCMrQSsp:btse4o3) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L123)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
>   bool iscrowd = 4;
> ```
Add a comment and an empty line in between
</blockquote></details>

Refer to crowd box in coco dataset
___
*[dgp/proto/annotations.proto, line 132 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmsttf0r_RD28_lUCx:-MpsNKfeBwiSBNVDF3VR:b2nign6) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L132)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> Frame index
> ```
Sample index?
</blockquote></details>

yes
___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-MpsNT250A3gvalR8Qjd:b1tqtiv) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

This field looks unnecessary to me. Since this is a base object and we should avoid storing top-level metadata (SceneDataset, Scene, Sample, etc) in this lowest level data container. IMO double linkage in the schema is redundant and we can always build a table or dictionary for in the datasetclass initialization.
</blockquote></details>

it is necessary otherwise it is hard for agentsnapshot to be associated with a frame.
___
*[dgp/proto/dataset.proto, line 146 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtrVp1JDayMFOMJLZ:-MpsNe0W9vKkpiocPjLr:b-tlhut1) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/dataset.proto#L146)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Add simple comment
</blockquote></details>

Road actors in the scene (Pedestrians, vehicles, etc)


<!-- Sent from Reviewable.io -->

2021-12-02 01:06 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 8 of 13 files reviewed, 25 unresolved discussions (waiting on @ChaoFang-TRI, @quincy-kh-chen, and @visakii-work)

___
*[dgp/proto/agent.proto, line 12 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmpxgo4eTDUfVdZaps:-Mpsenoz-X_XQmF4m51l:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L12)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

I would reorder this file by arranging the data containers in a bottom-up way i.e. from `AgentSnapshot2D/3D` to `AgentSnapshot` to `AgentSlice` to `AgentGroup` or vice versa (top-down). IMO it's more understandable. Currently it's unordered.
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 15 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmoWII2wDbRTibipi-:-Mpseo_y3-yx0Elr5kPn:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L15)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> scene
> ```
`Scene.`
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 20 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmonKsAbCTgVQHmdKQ:-MpseqOD1Qgkq2Pmw6nN:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L20)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

rm duplicated `without`
`For group without without unique names` -> `For the group without a unique names`?
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 24 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmp5Nw23PX8INn0hKO:-MpserFO946coZZDav21:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L24)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Following the convention, please end a sentence with a period.
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 41 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmpIakA8ecKoaqJ_eN:-MpsesXK8UTHqDVSvlPg:bm0h6n3) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L41)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

period

BTW why do we need `creation_date` for `AgentGroup`?
</blockquote></details>

@chaofang-tri ?
___
*[dgp/proto/agent.proto, line 75 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmr7w7821WrKKBhXkI:-Mpsewz23PALEOw82ZB4:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L75)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Let's elaborate what's `sample ID`. Referring to https://github.com/TRI-ML/dgp/blob/master/dgp/proto/sample.proto#L84?
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 91 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmroHIAbPTjz-rGz8o:-MpsexnDBf55NrZPXwNW:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L91)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

AgentTrack is a track of a single agent in the scene.
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 93 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmrgsv5Yl2qOOAhaiK:-MpseyFiAzVrVjQAqqVg:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L93)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

add empty lines between the fields below to follow the convention in this file.
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 123 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpms1Pq4n4yqRc8Z-2G:-MpseyvA58pLDslJ1D6U:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L123)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

Refer to crowd box in coco dataset
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 128 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsGHH4OHIvL0fx-mv:-MpsezkLD2W_J29IRgRP:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L128)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> list
> ```
/list/List/ 
Let's start a sentence with uppercase
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 128 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsCRk0suPhtfqElkA:-Mpsf-4d8vpoUL_MW6kB:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L128)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

/stored/store/
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 128 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsYVr5FJuHFSWxYAO:-Mpsf-vr3K8POYVRdQ2I:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L128)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> The schema
> ```
Could you elaborate what does `schema` refer to?
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 129 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsPZyASLZMkr7X9WW:-Mpsf0QM2g9GOZI0rjiW:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L129)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> i.e.,
> ```
/,parked car/ parked car/
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 152 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmuzvsDNo-joVMK-2P:-Mpsf1IuEu_R3NzNDgcd:b-29evh3) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L152)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Isn't `uint32` enough?
</blockquote></details>

@chaofang-tri mentioned earlier that it should do.
___
*[dgp/proto/annotations.proto, line 1 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmsl296iuREylin5mZ:-Mpsf5aiEO5V5UO7r98M:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L1)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

 keep `2019-2021`
</blockquote></details>

Done.
___
*[dgp/proto/annotations.proto, line 132 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmsttf0r_RD28_lUCx:-Mpsf684EU_7E6rQnue0:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L132)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.
___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mpsf6v58zj1zfT1-ZJU:b-wklkvr) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

it is necessary otherwise it is hard for agentsnapshot to be associated with a frame.
</blockquote></details>

Done. @quincy-kh-chen 
___
*[dgp/proto/dataset.proto, line 16  [...]

2021-12-02 03:10 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 8 of 13 files reviewed, 25 unresolved discussions (waiting on @ChaoFang-TRI, @quincy-kh-chen, and @visakii-work)

___
*[dgp/proto/ontology.proto, line 59 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmupBmDBFba-wjV7g2:-Mpt6kpsAQMa44BumA-n:bm0at4) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/ontology.proto#L59)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

@chaofang-tri ?
</blockquote></details>

both ok.


<!-- Sent from Reviewable.io -->

2021-12-02 18:53 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 5 of 13 files reviewed, 25 unresolved discussions (waiting on @ChaoFang-TRI, @quincy-kh-chen, and @visakii-work)

___
*[dgp/proto/agent.proto, line 41 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmpIakA8ecKoaqJ_eN:-MpwUJI99G2rsMJattOK:bvd02lw) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L41)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

@chaofang-tri ?
</blockquote></details>

Agent group is top level agent container. We want to have more info of creation and other metadata


<!-- Sent from Reviewable.io -->

2021-12-02 19:43 UTC, quincy-kh-chen requested changes
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 22 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @kuanleetri, and @visakii-work)

___
*[dgp/proto/agent.proto, line 91 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmroHIAbPTjz-rGz8o:-MpwbLBAAR2SkUknj3Q7:bvdzba8) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L91)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please add the docstring to the message.

```
// AgentTrack is the track of a single agent in the Scene.
message AgentTrack {
```
___
*[dgp/proto/agent.proto, line 128 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsYVr5FJuHFSWxYAO:-Mpwc2_UCk8yV9SfulgN:bx4sks2) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L128)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Didn't push the changes?
___
*[dgp/proto/agent.proto, line 129 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsPZyASLZMkr7X9WW:-Mpwc7YD00c68_56q0NF:bx4sks2) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L129)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Didn't push the changes?
___
*[dgp/proto/agent.proto, line 26 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwbuFbD0GDzHnyk6E2:-MpwbuFbD0GDzHnyk6E3:b2wxiy3) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L26)):*
> ```protobuf
>   // Other fields useful for downstream metric computation.
>   uint32 area = 3;
>   
> ```

rm heading spaces
___
*[dgp/proto/agent.proto, line 30 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwcdiA50DzxSnC09hP:-MpwcdiA50DzxSnC09hQ:b6muswb) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L30)):*
> ```
>   // Agent identifier
> ```
Let's elaborate this?
```
  // Instance identifier for this agent.
  // This needs to be unique in an image
```
___
*[dgp/proto/agent.proto, line 76 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwanc-Dj9fm3ZKVZjE:-Mpwanc-Dj9fm3ZKVZjF:b-3r0l64) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L76)):*
> ```protobuf
> }
> 
> message AgentsSlice {
> ```

Add some docstring to describe `AgentsSlice` message
___
*[dgp/proto/agent.proto, line 78 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwaxNa9L-2edzdPsZJ:-MpwaxNa9L-2edzdPsZK:b-7la3yp) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L78)):*
> ```
> ··
> ```
rm trailing spaces
___
*[dgp/proto/agent.proto, line 79 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwb1Z8CgniTfc7g4Va:-Mpwb1Z8CgniTfc7g4Vb:bpxuidz) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L79)):*
> ```
> agent slice
> ```
`/agent slice/AgentSlice/`
___
*[dgp/proto/agent.proto, line 79 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwb4g879WjS3BSk6G5:-Mpwb4g879WjS3BSk6G6:bfzieq4) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L79)):*
> ```protobuf
>   // Unique slice identifier (See dgp.idenfiers.proto)
>   // Copy from unique sample identifier (See dgp.sample.proto) to ensure one-one match 
>   // between a agent slice and sample
> ```

`/sample/Sample/`
___
*[dgp/proto/agent.proto, line 80 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwb6Un7KFzNmJXOahf:-Mpwb0NN5_tnyC_0OgOe:bcq44tl) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L80)):*
> ```
>  a
> ```
`/scene/Scene/`
___
*[dgp/proto/agent.proto, line 83 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwbA1W5T4iZbBgrPpi:-MpwbA1W5T4iZbBgrPpj:b-bshjvd) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L83)):*
> ```
> agents slice
> ```
ditto
___
*[dgp/proto/agent.proto, line 102 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwbeCMAMYlFTMlARou:-MpwbeCMAMYlFTMlARov:b7bpc6l) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L102)):*
> ```
> ···
> ```
rm heading spacesThis is used to store
___
*[dgp/proto/agent.proto, line 117 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwZiPSCqTm-sg9qtdI:-MpwZiPSCqTm-sg9qtdJ:b3a2cru) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L117)):*
> ```protobuf
> }
> 
> // All agents in a scene.
> ```

/scene/Scene/

`All agents in a scene.` ---> `AgentGroup encapsulates all Agents in a Scene.`?
___
*[dgp/proto/agent.proto, line 119 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpw_PWS5cWvRdHMalJD:-Mpw_PWS5cWvRdHMalJE:b-f047io) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L119)):*
> ```protobuf
> // All agents in a scene.
> message AgentGroup {
>   // Unique name for the group of agents in a scene.
> ```

/scene/Scene/
___
*[dgp/proto/agent.proto, line 135 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwa3yi1fe4xWDJQDr9:-Mpwa3yi1fe4xWDJQDrA:bhhxr9o) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L135)):*
> ```protobuf
>   string log = 3;
> 
>   // List of agent slices corresponding to this scene, each slice contains
> ```

Let's do `/scene/Scene/` for all scene in this file for consistency. 
___
*[dgp/proto/agent.proto, line 136 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwaHLR48gtwd-Chus9:-MpwaHLR48gtwd-ChusA:bfzieq4) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L136)):*
> ```protobuf
> 
>   // List of agent slices corresponding to this scene, each slice contains
>   // agent snapshots from one sample in the scene.
> ```

`/sample/Sample/`
___
*[dgp/proto/agent.proto, line 145 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwaRtw64v_6GHe0ibj:-MpwaRtw64v_6GHe0ibk:bhsa9mk) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L145)):*
> ```
> agent group
> ```
Let's do `/agent group/AgentGroup/`
___
*[dgp/proto/agent.proto, line 152 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwcN3OA8is2eEVSEjR:-MpwcN3OA8is2eEVSEjS:b-tfidxi) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L152)):*
> ```protobuf
>   // Maps dgp.proto.FeatureType (Agent_3D, EGO_INTENTION, etc) to the filename
>   // containing the ontology for the specific FeatureType/Task.
>   map<int32, string> feature_ontologies = 8;
> ```

Switch to `uint32`?
___
*[dgp/proto/agent.proto, line 158 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwcSMF7IuaRW4OT_Z1:-MpwcSMF7IuaRW4OT_Z2:b-tfidxi) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L158)):*
> ```protobuf
>   // Maps dgp.proto.AnnotationType (bounding_box_3d, etc) to the filename
>   // containing the ontology for the specific AgentType/Task.
>   map<int32, string> agent_ontologies = 9;
> ```

Switch to `uint32`?
___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mpwd88VDuVgS50X6gG6:b6uy6pk) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previo [...]

2021-12-02 20:50 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 22 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @kuanleetri, and @visakii-work)

___
*[dgp/proto/agent.proto, line 66 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpmqv5HAs_xbamO5IhG:-MpwuVPBDQl70uhGBOd1:b2nign6) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L66)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW is this the double link being used to trace back to which `AgentsSlice` includes this `AgentSnapshot`?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2021-12-02 20:58 UTC, chrisochoatri reviewed
+@chrisochoatri for review

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63#-:-Mpww5x99AhgLouVs2ok:biqrhe5)* status: all files reviewed, 22 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @kuanleetri, and @visakii-work)



<!-- Sent from Reviewable.io -->

2021-12-02 21:29 UTC, quincy-kh-chen requested changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 23 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @kuanleetri, and @visakii-work)

___
*[dgp/proto/agent.proto, line 67 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpx24uF0Vg9UuUUiaa1:-Mpx24uF0Vg9UuUUiaa2:b-ck4apl) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L67)):*
> ```
>   // Copy from sample ID to ensure one-one match between a agent slice and sample
>   // in a scene.
> ```
```
// Copy from Sample.id to ensure one-one match between a AgentSlice and Sample
// in a Scene.
```


<!-- Sent from Reviewable.io -->

2021-12-02 23:06 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 24 unresolved discussions (waiting on @chrisochoatri, @kuanleetri, and @quincy-kh-chen)

___
*[dgp/proto/agent.proto, line 91 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmroHIAbPTjz-rGz8o:-MpxOEv4EZKTF2_NbR8x:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L91)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Please add the docstring to the message.

```
// AgentTrack is the track of a single agent in the Scene.
message AgentTrack {
```

</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 128 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsYVr5FJuHFSWxYAO:-MpxOKcC6_NS-ruosxKj:b-oyn9xg) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L128)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Didn't push the changes?
</blockquote></details>

sorry, made changes 
___
*[dgp/proto/agent.proto, line 129 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmsPZyASLZMkr7X9WW:-MpxONlI6S-dXFu82ty8:b-sytf41) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/agent.proto#L129)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Didn't push the changes?
</blockquote></details>

sorry, changes should be visible now.
___
*[dgp/proto/agent.proto, line 26 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwbuFbD0GDzHnyk6E2:-MpxNzJxDuNBcdpQpa0c:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L26)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

rm heading spaces
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 30 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwcdiA50DzxSnC09hP:-MpxO-ra7iiyJHIEVr70:b499q7j) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L30)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
>   // Agent identifier
> ```
Let's elaborate this?
```
  // Instance identifier for this agent.
  // This needs to be unique in an image
```

</blockquote></details>

Changed
___
*[dgp/proto/agent.proto, line 45 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpxO126-kJrVBiHR9jF:-MpxO126-kJrVBiHR9jG:b-ez496v) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L45)):*
> ```protobuf
>   uint32 class_id = 1;
> 
>   // 3D box, the pose of box is in sensor coordinate.
> ```

addressed this, please lmk if it makes sense
___
*[dgp/proto/agent.proto, line 67 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpx24uF0Vg9UuUUiaa1:-MpxO8GL9w7JHuKDmlgu:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L67)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
>   // Copy from sample ID to ensure one-one match between a agent slice and sample
>   // in a scene.
> ```
```
// Copy from Sample.id to ensure one-one match between a AgentSlice and Sample
// in a Scene.
```
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 76 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwanc-Dj9fm3ZKVZjE:-MpxOBET7y40uPe2Ax_7:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L76)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Add some docstring to describe `AgentsSlice` message
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 78 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwaxNa9L-2edzdPsZJ:-MpxOBiL6t1FpbBx7swQ:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L78)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> ··
> ```
rm trailing spaces
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 79 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwb1Z8CgniTfc7g4Va:-MpxOCC50hGzddJyetUZ:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L79)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> agent slice
> ```
`/agent slice/AgentSlice/`
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 79 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwb4g879WjS3BSk6G5:-MpxOCa20g37NmWy7aGq:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L79)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

`/sample/Sample/`
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 80 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwb6Un7KFzNmJXOahf:-MpxOD-x3HZO92ta41q0:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L80)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
>  a
> ```
`/scene/Scene/`
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 83 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwbA1W5T4iZbBgrPpi:-MpxODapCJAUx8PJxLWS:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L83)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> agents slice
> ```
ditto
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 102 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwbeCMAMYlFTMlARou:-MpxOFQKAelP6NIEweMt:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L102)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> ···
> ```
rm heading spacesThis is used to store
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 117 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwZiPSCqTm-sg9qtdI:-MpxOGEh7lFAjSy_EB1G:b-77ru5q) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L117)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

/scene/Scene/

`All agents in a scene.` ---> `AgentGroup encapsulates all Agents in a Scene.`?
</blockquote></details>

Done. Also yes, its all agents in a scene
___
*[dgp/proto/agent.proto, line 119 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpw_PWS5cWvRdHMalJD:-MpxOJasESc2QMYo7cNk:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L119)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

/scene/Scene/
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 135 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwa3yi1fe4xWDJQDr9:-MpxOUAV4r4vwI0eo6xE:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L135)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Let's do `/scene/Scene/` for all scene in this file for consistency. 
</blockquote></details>

Done.
___
*[dgp/proto/agent.proto, line 136 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-MpwaHLR48gtwd-Chus9:-MpxOUXh0i_GTBO [...]

2021-12-03 01:30 UTC, kuanleetri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 23 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @quincy-kh-chen)

___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mpxtw6e71F_eHxnf0Go:b-80wrtu) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

@kuanleetri @chrisochoatri what's your thoughts here?
IMO we shouldn't put the top-level data containers' metadata to the low-level data containers. Ideally, this should happen during the agent dataset instantiation.

One workaround is to add `metadata` field to encapsulate arbitrary metadata here to serve different use cases (instead of explicitly specifying top-level sample_idx here). Would that work?

Add:
```
  // Sample-specific metadata
  // Optional, miscellaneous enriched annotations
  map<string, google.protobuf.Any> metadata = 4;
``` 
</blockquote></details>

I kinda agree with quincy, putting sample id in the bbox level is a bit weird. I also understand why agentsnapshot needs this 'cause that will save lots of fetching time. So maybe a workaround from quincy is doable?


<!-- Sent from Reviewable.io -->

2021-12-03 01:40 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 23 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-MpxviE5-ZAQxYyifZ4v:b-lwv4dg) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

I kinda agree with quincy, putting sample id in the bbox level is a bit weird. I also understand why agentsnapshot needs this 'cause that will save lots of fetching time. So maybe a workaround from quincy is doable?
</blockquote></details>

@kuanleetri @quincy-kh-chen In agent-centric dataset, sample ID is not top level metadata anymore. It is equivalent to track-id which help to group agents into a track. sample ID help to group agent into frame. I intent to extend BoundingBox2D and BoundingBox3D with sample ID so they could be legit container for AgentSnapshot2D and AgentSnapShot3D


<!-- Sent from Reviewable.io -->

2021-12-03 01:45 UTC, kuanleetri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 23 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-MpxxUzB-seAPrBqr0v2:b-hpvmn4) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

@kuanleetri @quincy-kh-chen In agent-centric dataset, sample ID is not top level metadata anymore. It is equivalent to track-id which help to group agents into a track. sample ID help to group agent into frame. I intent to extend BoundingBox2D and BoundingBox3D with sample ID so they could be legit container for AgentSnapshot2D and AgentSnapShot3D
</blockquote></details>

Yeah but sample_id is not the same level of track_id from structure perspective. Using map you can still do `metadata['sample_id'] = xx`, or even more attributes?


<!-- Sent from Reviewable.io -->

2021-12-03 01:51 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 23 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mpxygm5AeH7zrKmkhck:b-xs0g8) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

Yeah but sample_id is not the same level of track_id from structure perspective. Using map you can still do `metadata['sample_id'] = xx`, or even more attributes?
</blockquote></details>

 @quincy-kh-chen @kuanleetri Looking at this again, I think we don't have to have sample index in BoundingBox3D proto, we can remove it. But when we need to maintain sample index field just like track-id field. Sounds good?


<!-- Sent from Reviewable.io -->

2021-12-03 01:52 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 23 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-MpxzOQV9WimAEBKIqLH:b-2hpcsa) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

 @quincy-kh-chen @kuanleetri Looking at this again, I think we don't have to have sample index in BoundingBox3D proto, we can remove it. But when we need to maintain sample index field just like track-id field. Sounds good?
</blockquote></details>

We could have sample id in BoundingBox3D class similar to instance id


<!-- Sent from Reviewable.io -->

2021-12-03 01:55 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 23 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mpy-5Ty0KZtvPhmMChP:b-7wbs28) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

We could have sample id in BoundingBox3D class similar to instance id
</blockquote></details>

@visakii-work you can simply delete this filed in this PR. We can change the dataclass PR  a little.


<!-- Sent from Reviewable.io -->

2021-12-03 02:06 UTC, kuanleetri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 23 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mpy-R3H2TuzdYD3-UQh:b-stx20i) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

@visakii-work you can simply delete this filed in this PR. We can change the dataclass PR  a little.
</blockquote></details>

I think in API level I'm not super against it.


<!-- Sent from Reviewable.io -->

2021-12-03 02:53 UTC, chrisochoatri requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 26 unresolved discussions (waiting on @quincy-kh-chen and @visakii-work)

___
*[dgp/proto/agent.proto, line 28 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpy5iNj55Xy16fSYw8f:-Mpy5iNj55Xy16fSYw8g:b-40w7kg) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L28)):*
> ```protobuf
> 
>   // Refer to crowd box in coco dataset.
>   bool iscrowd = 4;
> ```

nit: why do we need this? is this legacy?
___
*[dgp/proto/agent.proto, line 47 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-MpyAfP51q9idXJmi3Iw:-MpyAfP51q9idXJmi3Ix:b-682tlm) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L47)):*
> ```protobuf
> 
>   // 3D box, the pose of box is in sensor coordinate.
>   BoundingBox3D box = 2;
> ```

Why not use BoundingBox3DAnnotation? Also maybe this could be a repeated field. A single bounding box does not represent some agents we care about, i.e., accordion bus, 18 wheeler etc. This might allow us to rethink of instance_id as the an instance of a bounding box, and as an agent as a higher level object. 
___
*[dgp/proto/agent.proto, line 106 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpy70iT-xbCSOaw3hgR:-Mpy70iUBP_tseoqqxcU:bldmcwl) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L106)):*
> ```protobuf
> 
>   // List of AgentSnapshots encapsulated in the AgentTrack.
>   repeated AgentSnapshot agent_snapshots = 3;
> ```

nit: question, can an agent have multiple tracks?
___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mpy8i6xAGIO7r_Nmql-:b-uj4jx2) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

I think in API level I'm not super against it.
</blockquote></details>

I sort of agree with Quincy here, but I don't like the idea of adding another meta data field to bounding box 3d because we have one already in BoundingBox3DAnnotation. Is the instance_id in BoundingBox3DAnnotation not sufficient?


<!-- Sent from Reviewable.io -->

2021-12-03 03:17 UTC, quincy-kh-chen requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 6 unresolved discussions (waiting on @quincy-kh-chen and @visakii-work)

___
*[dgp/proto/agent.proto, line 79 at r4](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpwb1Z8CgniTfc7g4Va:-MpyGnnG2OnViD6STFlc:bjcllfw) ([raw file](https://github.com/tri-ml/dgp/blob/775dd013cb52103e9c7ce78e800837b42e0bddb6/dgp/proto/agent.proto#L79)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

Done.
</blockquote></details>

NIT: ends with a period
___
*[dgp/proto/agent.proto, line 97 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-MpyH-0s5IUjJKkKTf-I:-MpyH-0t8m1gbbisTlbV:b-5ijdat) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L97)):*
> ```
> a
> ```
NIT the track instead of a track? Would it be possible that a single `Agent` has multiple tracks in a `Scene`?


<!-- Sent from Reviewable.io -->

2021-12-03 03:17 UTC, ChaoFang-TRI reviewed
@quincy-kh-chen @visakii-work Maybe it is good to change your avatar to your pic, seems difficult to distinguish you too, lol

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63#-:-MpyHo9tCkLJ6xp3zPE2:b2ostw1)* status: all files reviewed, 6 unresolved discussions (waiting on @quincy-kh-chen and @visakii-work)



<!-- Sent from Reviewable.io -->

2021-12-03 03:22 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 6 unresolved discussions (waiting on @chrisochoatri, @quincy-kh-chen, and @visakii-work)

___
*[dgp/proto/agent.proto, line 28 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpy5iNj55Xy16fSYw8f:-MpyI9lA2dsSWQ8HFyjV:b-vrfi8y) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L28)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: why do we need this? is this legacy?
</blockquote></details>

yeah, to be backward compatible with agents from 2D annotation. I am not super against to remove it. 
___
*[dgp/proto/agent.proto, line 47 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-MpyAfP51q9idXJmi3Iw:-MpyIPVg6sNw-XoCNgYQ:b-g54t5n) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L47)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

Why not use BoundingBox3DAnnotation? Also maybe this could be a repeated field. A single bounding box does not represent some agents we care about, i.e., accordion bus, 18 wheeler etc. This might allow us to rethink of instance_id as the an instance of a bounding box, and as an agent as a higher level object. 
</blockquote></details>

@chrisochoatri AgentSnapshot3D is similar container of BoundingBox3DAnnotation so it has a BoundingBox3D field. @quincy-kh-chen How did we handle connected objects in dgp? Same instance ID?


<!-- Sent from Reviewable.io -->

2021-12-03 04:53 UTC, quincy-kh-chen reviewed
@chaofang-tri updated my profile lol

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63#-:-MpyctyC7AhrEatAoNOZ:b-ic5inx)* status: all files reviewed, 6 unresolved discussions (waiting on @chrisochoatri, @quincy-kh-chen, and @visakii-work)



<!-- Sent from Reviewable.io -->

2021-12-03 04:54 UTC, kuanleetri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 6 unresolved discussions (waiting on @chrisochoatri, @quincy-kh-chen, and @visakii-work)

___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mpyc-ue87Yxj6wZB9G6:bc9dykg) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

I sort of agree with Quincy here, but I don't like the idea of adding another meta data field to bounding box 3d because we have one already in BoundingBox3DAnnotation. Is the instance_id in BoundingBox3DAnnotation not sufficient?
</blockquote></details>

`instance_id` is for an object, `sample_id` is for a timestamp sample. I think the purpose is to link an identical object across different samples, and sample_id in boundingbox3d can make the index building more efficient (for agent use cases). My cents is that schema should be pretty strict to the level, but API/class level can be more flexible. thoughts? 


<!-- Sent from Reviewable.io -->

2021-12-03 05:05 UTC, quincy-kh-chen requested changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 6 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @kuanleetri, and @visakii-work)

___
*[dgp/proto/agent.proto, line 47 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-MpyAfP51q9idXJmi3Iw:-MpydQgJ-R5KdP9jS2TX:b2s7st4) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L47)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

@chrisochoatri AgentSnapshot3D is similar container of BoundingBox3DAnnotation so it has a BoundingBox3D field. @quincy-kh-chen How did we handle connected objects in dgp? Same instance ID?
</blockquote></details>

@chaofang-tri don't think we have connected objects. IMO we can store the "link" in attributes field (https://github.com/TRI-ML/dgp/blob/master/dgp/proto/annotations.proto#L147) or add a metadata field to message `BoundingBox2DAnnotation /BoundingBox3DAnnotation`  


@chrisochoatri good point! Looks to me it is reasonable to use `BoundingBox3DAnnotation`. But no strong opinion here.
___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mpyekqc4asuGtQtZP-b:b3mcg7w) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

`instance_id` is for an object, `sample_id` is for a timestamp sample. I think the purpose is to link an identical object across different samples, and sample_id in boundingbox3d can make the index building more efficient (for agent use cases). My cents is that schema should be pretty strict to the level, but API/class level can be more flexible. thoughts? 
</blockquote></details>

Agreed with @kuanleetri 
We can add an additional metadata field (or even explicit sample id) to `AgentSnapshot3D` to store the box->sample double linkage if we really need it. But we shouldn't add this field in this base data container (my two cents).


<!-- Sent from Reviewable.io -->

2021-12-03 17:51 UTC, chrisochoatri requested changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 6 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @kuanleetri, @quincy-kh-chen, and @visakii-work)

___
*[dgp/proto/agent.proto, line 47 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-MpyAfP51q9idXJmi3Iw:-Mq0Oj8iDU4Nfanfpr-a:bfwfwgc) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L47)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

@chaofang-tri don't think we have connected objects. IMO we can store the "link" in attributes field (https://github.com/TRI-ML/dgp/blob/master/dgp/proto/annotations.proto#L147) or add a metadata field to message `BoundingBox2DAnnotation /BoundingBox3DAnnotation`  


@chrisochoatri good point! Looks to me it is reasonable to use `BoundingBox3DAnnotation`. But no strong opinion here.
</blockquote></details>

@chaofang-tri  I see. This proto seems almost identical to BoundingBox3D annotation, just with features + feature_type instead of the attributes dictionary. Any possibility to just use BoundingBox3D instead of this proto? no strong opinions though, just asking.


<!-- Sent from Reviewable.io -->

2021-12-03 18:06 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 6 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @kuanleetri, and @visakii-work)

___
*[dgp/proto/agent.proto, line 47 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-MpyAfP51q9idXJmi3Iw:-Mq0RcwE86blgwPbcy6m:b-633w67) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L47)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

@chaofang-tri  I see. This proto seems almost identical to BoundingBox3D annotation, just with features + feature_type instead of the attributes dictionary. Any possibility to just use BoundingBox3D instead of this proto? no strong opinions though, just asking.
</blockquote></details>

@chrisochoatri Actually the features ontology is important improvement to support feature versioning.  I intentionally use agents instead of annotation as well since it is a common way among various datasets like Argoverse, l5 data, etc. So, I recommend to have a AgentSnapshop proto instead of extending BoundingBox3DAnnotation proto. If we use BoundingBox3DAnnotation for agents then it is very difficult to deprecate it in the future.


<!-- Sent from Reviewable.io -->

2021-12-03 18:25 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 6 unresolved discussions (waiting on @chrisochoatri, @quincy-kh-chen, and @visakii-work)

___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-Mq0WK4B7g2ync9vvadq:b-i2v3ne) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Agreed with @kuanleetri 
We can add an additional metadata field (or even explicit sample id) to `AgentSnapshot3D` to store the box->sample double linkage if we really need it. But we shouldn't add this field in this base data container (my two cents).
</blockquote></details>

@chaofang-tri would it be okay to delete this field in bbox? do we need to add anything in AgentSnapshot3D then? or would modifying agent dataclass PR be sufficient without changing schema in future


<!-- Sent from Reviewable.io -->

2021-12-03 18:26 UTC, chrisochoatri requested changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 6 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @quincy-kh-chen, and @visakii-work)

___
*[dgp/proto/agent.proto, line 47 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-MpyAfP51q9idXJmi3Iw:-Mq0WNU74b1Sh-o-xHKJ:b-lo0tjo) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L47)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

@chrisochoatri Actually the features ontology is important improvement to support feature versioning.  I intentionally use agents instead of annotation as well since it is a common way among various datasets like Argoverse, l5 data, etc. So, I recommend to have a AgentSnapshop proto instead of extending BoundingBox3DAnnotation proto. If we use BoundingBox3DAnnotation for agents then it is very difficult to deprecate it in the future.
</blockquote></details>

I see. But are we not duplicating some data now? What keeps a class/instance id in sync between a BoundingBox3DAnnotation and an AgentSnapshot3D that reference the same cuboid? Is it possible? (or maybe this is a feature? ) that we could end up with a cuboid referenced in the lidar datum' that has class id of a car, and in the agent snapshot has class id of a Corolla (or something else)? My viewpoint is that agents should be extra meta data around existing annotations, not an alternate annotation. 


<!-- Sent from Reviewable.io -->

2021-12-05 18:35 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: 10 of 13 files reviewed, 6 unresolved discussions (waiting on @chrisochoatri, @quincy-kh-chen, and @visakii-work)

___
*[dgp/proto/agent.proto, line 47 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-MpyAfP51q9idXJmi3Iw:-MqArMh92Enmt-KzrlM0:b-g1ax6f) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L47)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

I see. But are we not duplicating some data now? What keeps a class/instance id in sync between a BoundingBox3DAnnotation and an AgentSnapshot3D that reference the same cuboid? Is it possible? (or maybe this is a feature? ) that we could end up with a cuboid referenced in the lidar datum' that has class id of a car, and in the agent snapshot has class id of a Corolla (or something else)? My viewpoint is that agents should be extra meta data around existing annotations, not an alternate annotation. 
</blockquote></details>

Yes, in backfill code, we keep the class/istance id synced. 
___
*[dgp/proto/annotations.proto, line 133 at r1](https://reviewable.io/reviews/tri-ml/dgp/63#-MpmtMa44SgXW3I2Sj7P:-MqAs6aG5j9X1k-oo0uj:b4zwq2t) ([raw file](https://github.com/tri-ml/dgp/blob/9fcdaabd26d6f879141294b785b108740e81e294/dgp/proto/annotations.proto#L133)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

@chaofang-tri would it be okay to delete this field in bbox? do we need to add anything in AgentSnapshot3D then? or would modifying agent dataclass PR be sufficient without changing schema in future
</blockquote></details>

@visakii-work yes, just delete the field in this PR.


<!-- Sent from Reviewable.io -->

2021-12-06 19:36 UTC, quincy-kh-chen approved these changes
@visakii-work let's `build-proto` again to ensure the compiled protos are up-to-date
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63#-:-MqGEab_6L-kdyOpZqmX:b-czn0c7)* status: all files reviewed, 3 unresolved discussions (waiting on @chrisochoatri and @visakii-work)



<!-- Sent from Reviewable.io -->

2021-12-06 20:14 UTC, chrisochoatri requested changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 2 unresolved discussions (waiting on @ChaoFang-TRI and @visakii-work)

___
*[dgp/proto/agent.proto, line 28 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpy5iNj55Xy16fSYw8f:-MqGMm2HDobHa8hi-gk1:btxfve1) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L28)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

yeah, to be backward compatible with agents from 2D annotation. I am not super against to remove it. 
</blockquote></details>

no strong feelings, up to you.
___
*[dgp/proto/agent.proto, line 47 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-MpyAfP51q9idXJmi3Iw:-MqGNAZLC5YjrVBg7Ybi:bue4hgy) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L47)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

Yes, in backfill code, we keep the class/istance id synced. 
</blockquote></details>

after our discussion I understand this more as an alternate annotation, I won't block over this.


<!-- Sent from Reviewable.io -->

2021-12-06 20:59 UTC, visakii-work reviewed
@quincy-kh-chen Its up to date!

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63#-:-MqGXlmu6yHuP26PHfmN:b7g25ty)* status: all files reviewed, 2 unresolved discussions (waiting on @ChaoFang-TRI and @visakii-work)



<!-- Sent from Reviewable.io -->

2021-12-06 23:43 UTC, quincy-kh-chen approved these changes
@visakii-work let's rebase onto master and this PR should be ready to be merged. Thank you!

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63#-:-MqH7BwxA5MbpSZYAUse:bn27w2y)* status: all files reviewed, 2 unresolved discussions (waiting on @ChaoFang-TRI and @visakii-work)



<!-- Sent from Reviewable.io -->

2021-12-07 00:21 UTC, visakii-work reviewed
@quincy-kh-chen done. thanks

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63#-:-MqHG8Vq8cX3_9l3DyQc:b-92ee4u)* status: all files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @visakii-work)

___
*[dgp/proto/agent.proto, line 28 at r5](https://reviewable.io/reviews/tri-ml/dgp/63#-Mpy5iNj55Xy16fSYw8f:-MqH4MYsAhsWjeAMWXHf:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/8f253d7832bfa4004a19d49937d1503ccd47fb18/dgp/proto/agent.proto#L28)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

no strong feelings, up to you.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-07 01:22 UTC, chrisochoatri reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  assuming CI passes

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63#-:-MqHTr1s7VZDBe0Sp8Vq:budbopf)* status: all files reviewed, 1 unresolved discussion (waiting on @visakii-work)



<!-- Sent from Reviewable.io -->

2021-12-07 01:22 UTC, chrisochoatri approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/63)* status: all files reviewed, 1 unresolved discussion (waiting on @visakii-work)



<!-- Sent from Reviewable.io -->

2021-12-07 20:07 UTC, merged