feat: add agent class and support
TRI-ML/dgp pull request #67
Opened 2021-12-01 19:54 UTC by visakii-work

2021-12-17 21:23 UTC, ChaoFang-TRI reviewed
Seems may proto files are reverted, I think it is not intended, right?

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67#-:-Mr9GfRU1mxUKcJ1EoT2:bvzbjs0)* status: 0 of 38 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-20 17:30 UTC, visakii-work reviewed
Ah these are reverted back to master branch proto, i made some change to this PR before proto was merged. 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67#-:-MrNsGRwBE8rjWlw-tI5:bjc953p)* status: 0 of 38 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-21 18:08 UTC, ChaoFang-TRI requested changes
Please reorganize manually the agent json to avoid duplication jsons. I think the easiest way is to keep one agent json and manually modify agent dataset json

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67#-:-MrTADqfCTdzkbPHdJKp:b-9f8oza)* status: 0 of 38 files reviewed, 1 unresolved discussion (waiting on @ChaoFang-TRI and @visakii-work)

___
*[dgp/datasets/agent_dataset.py, line 537 at r4](https://reviewable.io/reviews/tri-ml/dgp/67#-MrT8fh8AAOD1odsdzdr:-MrT8fh8AAOD1odsdzds:b-e3sp13) ([raw file](https://github.com/tri-ml/dgp/blob/236f126bd50cbb964e46facc16548bde2e86d38c/dgp/datasets/agent_dataset.py#L537)):*
> ```Python
>             self._build_agent_index()
> 
>         super().__init__(agent_metadata, agent_groups=agent_groups)
> ```

This line shall be moved before "if batch_per_agent:" line


<!-- Sent from Reviewable.io -->

2021-12-22 21:08 UTC, visakii-work reviewed
I manually changed the agent json's. 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67#-:-MrYyKnl4IKNI-K4zRwo:bbi1anh)* status: 0 of 38 files reviewed, 1 unresolved discussion (waiting on @ChaoFang-TRI)

___
*[dgp/datasets/agent_dataset.py, line 537 at r4](https://reviewable.io/reviews/tri-ml/dgp/67#-MrT8fh8AAOD1odsdzdr:-MrYyJSC15LuJCaqh-L0:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/236f126bd50cbb964e46facc16548bde2e86d38c/dgp/datasets/agent_dataset.py#L537)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

This line shall be moved before "if batch_per_agent:" line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-24 01:04 UTC, ChaoFang-TRI requested changes
> Reviewed 11 of 38 files at r1, 21 of 24 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: all files reviewed, 4 unresolved discussions (waiting on @ChaoFang-TRI and @visakii-work)

___
*[dgp/constants.py, line 20 at r5](https://reviewable.io/reviews/tri-ml/dgp/67#-MrdxQn6Bzjosk05MQIj:-MrdxQn6Bzjosk05MQIk:b-8h1uqw) ([raw file](https://github.com/tri-ml/dgp/blob/eca63bf0e1e21ed2eb47a2efab91352e9e66ae37/dgp/constants.py#L20)):*
> ```Python
> 
> # Provide supported annotations for each type of datum
> DATUM_TYPE_TO_SUPPORTED_ANNOTATION_TYPE = OrderedDict({
> ```

Is it part of scope of this PR?
___
*[dgp/agents/agent_3d.py, line 14 at r5](https://reviewable.io/reviews/tri-ml/dgp/67#-Mrdx_sn2skwJi4LbFuE:-Mrdx_sn2skwJi4LbFuF:b-l9n9kf) ([raw file](https://github.com/tri-ml/dgp/blob/eca63bf0e1e21ed2eb47a2efab91352e9e66ae37/dgp/agents/agent_3d.py#L14)):*
> ```Python
> 
> class AgentSnapshot3DList(AgentSnapshotList):
>     """Container for 3D agent list .
> ```

extra space
___
*[dgp/datasets/agent_dataset.py, line 734 at r5](https://reviewable.io/reviews/tri-ml/dgp/67#-MrdxpXa1UeRrV9VXGoZ:-MrdxpXa1UeRrV9VXGo_:b4b2afq) ([raw file](https://github.com/tri-ml/dgp/blob/eca63bf0e1e21ed2eb47a2efab91352e9e66ae37/dgp/datasets/agent_dataset.py#L734)):*
> ```Python
>     """Dataset for agent-centric prediction or planning use cases. It provide two mode of accessing agent, by track
>     and by frame. If 'batch_per_agent' is set true, then the data iterate per track, note, the length of the track
>     could vary. Otherwise, the data iterate per frame and each sample contains all agents in the fram.
> ```

typo frame


<!-- Sent from Reviewable.io -->

2021-12-24 01:05 UTC, ChaoFang-TRI submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  Approve with small comments! 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67#-:-Mrdy5EWCHN29IONnabK:b-w9gyim)* status: all files reviewed, 4 unresolved discussions (waiting on @ChaoFang-TRI and @visakii-work)



<!-- Sent from Reviewable.io -->

2022-01-04 18:32 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: all files reviewed, 3 unresolved discussions (waiting on @ChaoFang-TRI)

___
*[dgp/constants.py, line 20 at r5](https://reviewable.io/reviews/tri-ml/dgp/67#-MrdxQn6Bzjosk05MQIj:-MsaLxC47IIGKIhdMw03:b-b6b8mj) ([raw file](https://github.com/tri-ml/dgp/blob/eca63bf0e1e21ed2eb47a2efab91352e9e66ae37/dgp/constants.py#L20)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

Is it part of scope of this PR?
</blockquote></details>

Yes, without this I cannot load the agent dataset. and tests fails
___
*[dgp/agents/agent_3d.py, line 14 at r5](https://reviewable.io/reviews/tri-ml/dgp/67#-Mrdx_sn2skwJi4LbFuE:-MsaM79sEJ5ZSts1GDPC:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/eca63bf0e1e21ed2eb47a2efab91352e9e66ae37/dgp/agents/agent_3d.py#L14)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-05 21:54 UTC, ChaoFang-TRI submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @visakii-work)



<!-- Sent from Reviewable.io -->

2022-01-05 23:07 UTC, chrisochoatri requested changes
> Reviewed 2 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 36 of 38 files reviewed, 21 unresolved discussions (waiting on @ChaoFang-TRI and @visakii-work)

___
*[dgp/constants.py, line 1 at r6](https://reviewable.io/reviews/tri-ml/dgp/67#-Msg-knT3M6zZ6I85laR:-Msg-knT3M6zZ6I85laS:b2gosso) ([raw file](https://github.com/tri-ml/dgp/blob/1b5c899491ebad890abdd3ec79c4c924f27eaf7d/dgp/constants.py#L1)):*
> ```Python
> # Copyright 2021 Toyota Research Institute. All rights reserved.
> ```

nit: do we need to update these for 2022?



_Code quote:_
```Python
2021
```
___
*[dgp/agents/__init__.py, line 1 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgHFd3CJC3khL_qWY4:-MsgHFd3CJC3khL_qWY5:b-wsq8tv) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/__init__.py#L1)):*
> ```Python
> # Copyright 2021 Toyota Research Institute. All rights reserved.
> ```

nit: ditto, maybe 2021-2022?



_Code quote:_
```Python
2021
```
___
*[dgp/agents/agent_2d.py, line 12 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgIf_i1dQH-iXiH6Dy:-MsgIf_i1dQH-iXiH6Dz:b-iackb8) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L12)):*
> ```Python
> 
> class AgentSnapshot2DList(AgentSnapshotList):
>     """Container for 2D agent list .
> ```

nit: space
___
*[dgp/agents/agent_2d.py, line 19 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgJ7_h8yc3GuqxSADJ:-MsgJ7_h8yc3GuqxSADK:b-s2qw0d) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L19)):*
> ```Python
>         Ontology for 2D bounding box tasks.
> 
>     boxlist: list[BoundingBox2D]
> ```

nit: does it make sense to support BoundingBox2dAnnotationList?



_Code quote:_
```Python
list[BoundingBox2D]
```
___
*[dgp/agents/agent_2d.py, line 25 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgIoIz3MVE20FMNgK4:-MsgIoIz3MVE20FMNgK5:bvr0h03) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L25)):*
> ```Python
>     def __init__(self, ontology, boxlist):
>         super().__init__(ontology)
>         assert isinstance(self._ontology, BoundingBoxOntology), "Trying to load AgentSnapshotList with wrong type of " \
> ```

I think you meant AgentSnapshot2DList here



_Code quote:_
```Python
AgentSnapshotList
```
___
*[dgp/agents/agent_2d.py, line 31 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgJwC53e07SCqSX-J6:-MsgJwC53e07SCqSX-J7:b32vbr) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L31)):*
> ```Python
>             assert isinstance(
>                 box, BoundingBox2D
>             ), f"Can only instantiate an agent snapshot list from a list of BoundingBox3D, not {type(box)}"
> ```

2D



_Code quote:_
```Python
3D
```
___
*[dgp/agents/agent_2d.py, line 74 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgKItb1761axILyClY:-MsgKItcCjauusvjwhf-:bhje7ca) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L74)):*
> ```Python
>                     color=ontology.colormap[agent_snapshot_2d.agent_snapshot_2D.class_id],
>                     attributes=dict([(feature_ontology.id_to_name[feature_id], feature)
>                                      for feature_id, feature in enumerate(agent_snapshot_2d.agent_snapshot_2D.features)]
> ```

nit:  minor but I think you could just use comprehension for the dictionary directly here?
```python
attributes = { feature_ontolty.id_to_name[feature_id]: feature for feature_id, feature in enumerate(agent_snapshot_2d.agent_snapshot_2D.features) }
```



_Code quote:_
```Python
                    attributes=dict([(feature_ontology.id_to_name[feature_id], feature)
                                     for feature_id, feature in enumerate(agent_snapshot_2d.agent_snapshot_2D.features)]
                                    ),
```
___
*[dgp/agents/agent_3d.py, line 27 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgLNd--xFS1CV3ZyEC:-MsgLNd--xFS1CV3ZyED:b-7ropln) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_3d.py#L27)):*
> ```Python
>     def __init__(self, ontology, boxlist):
>         super().__init__(ontology)
>         assert isinstance(self._ontology, BoundingBoxOntology), "Trying to load AgentSnapshotList with wrong type of " \
> ```

ditto



_Code quote:_
```Python
AgentSnapshotList
```
___
*[dgp/agents/base_agent.py, line 8 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgMALA3IuWwxy8bqF6:-MsgMALA3IuWwxy8bqF7:b-wcp4yl) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/base_agent.py#L8)):*
> ```Python
> 
> 
> class AgentSnapshotList(ABC):
> ```

nit: if all agents are required to have a boxlist member that have attributes, instance ids, and class ids, you could consider moving those properties here maybe, though would limit the types of future agents you could define.
___
*[dgp/datasets/agent_dataset.py, line 1 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgNoT64LdA80k_1Umo:-MsgNoT64LdA80k_1Ump:b-tciejt) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L1)):*
> ```Python
> # Copyright 2021 Toyota Research Institute.  All rights reserved.
> ```

nit: ditto, though maybe this needs its own PR to update all the files



_Code quote:_
```Python
2021
```
___
*[dgp/datasets/agent_dataset.py, line 229 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgOSD98RTTNpVnvkDo:-MsgOSD98RTTNpVnvkDp:b-uhbn1k) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L229)):*
> ```Python
>     """Object-oriented container for holding agent information from a scene.
>     """
>     RANDOM_STR = ''.join([str(random.randint(0, 9)) for _ in range(5)])
> ```

This sometimes causes problems if using multiprocessing spawn since each process re imports the files. We have an optional environment variable you can set to override the randomness, see base_dataset.py SceneContainer. 



_Code quote:_
```Python
RANDOM_STR = ''.join([str(random.randint(0, 9)) for _ in range(5)])
```
___
*[dgp/datasets/agent_dataset.py, line 385 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgQIl85AKJGvv-1qoF:-MsgQIl85AKJGvv-1qoG:bp7rvdd) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L385)):*
> ```Python
>             return []
> 
>         agents_slices_file = os.path.join(self.directory, agent_slices_path)
> ```

I think I missed it, but does this still work as intended if self.directory is None since directory is marked as optional in __init__.



_Code quote:_
```Python
self.directory
```
___
*[dgp/datasets/agent_dataset.py, line 452 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgNYbY2nXXeJYeztva:-MsgNYbY2nXXeJYeztvb:b64tvvh) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L452)):*
> ```Python
> 
>     """
>     def __init__(
> ```

can you add use_diskcache as an option?
___
*[dgp/datasets/agent_dataset.py, line 491 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgNQVtDI6hSihsA2YU:-MsgNQVtDI6hSihsA2YV:b5ocmt1) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L491)):*
> ```Python
>         self.selected_datums = [_d.lower() for _d in datum_names]
>         if len(self.selected_datums) != 0:
>             self.synchronized_dataset = SynchronizedSceneDataset(
> ```

not sure if it would be possible to expose the rest of the parameters for synchronized scene dataset? such as use_diskcache, accumulation etc.



_Code quote:_
```Pyth [...]

2022-01-05 23:19 UTC, chrisochoatri requested changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 36 of 38 files reviewed, 22 unresolved discussions (waiting on @ChaoFang-TRI and @visakii-work)

___
*[dgp/datasets/agent_dataset.py, line 219 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgXQpZ-yFLNrFWLcz8:-MsgXQpZ-yFLNrFWLcz9:b-b8ffn7) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L219)):*
> ```Python
>         logging.debug('Hashing dataset with dataset directory, split and datum-index')
>         return int(
>             hashlib.md5(
> ```

super nit: maybe sha1?



_Code quote:_
```Python
md5
```


<!-- Sent from Reviewable.io -->

2022-01-10 19:11 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 36 of 38 files reviewed, 18 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @visakii-work)

___
*[dgp/agents/__init__.py, line 1 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgHFd3CJC3khL_qWY4:-Mt4NGhLEr0MPD1FYWDi:bw02sjv) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/__init__.py#L1)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: ditto, maybe 2021-2022?
</blockquote></details>

Yup made the change. 
___
*[dgp/agents/agent_2d.py, line 25 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgIoIz3MVE20FMNgK4:-Mt4NMvK9-cj691JDmwS:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L25)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

I think you meant AgentSnapshot2DList here
</blockquote></details>

Done.
___
*[dgp/agents/agent_2d.py, line 31 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgJwC53e07SCqSX-J6:-Mt4NN_xCRD-jLzCs_Td:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L31)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

2D
</blockquote></details>

Done.
___
*[dgp/agents/agent_3d.py, line 27 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgLNd--xFS1CV3ZyEC:-Mt4NQG45AFRyFD9itfc:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_3d.py#L27)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[dgp/agents/base_agent.py, line 8 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgMALA3IuWwxy8bqF6:-Mt4NRnlBWoqkUe7nXwP:b-ana1sa) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/base_agent.py#L8)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: if all agents are required to have a boxlist member that have attributes, instance ids, and class ids, you could consider moving those properties here maybe, though would limit the types of future agents you could define.
</blockquote></details>

I think the reason was that future agents would be limited. @chaofang-tri ?
___
*[dgp/datasets/agent_dataset.py, line 219 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgXQpZ-yFLNrFWLcz8:-Mt4Ndks07PbSRTTI878:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L219)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

super nit: maybe sha1?
</blockquote></details>

Done.
___
*[dgp/datasets/agent_dataset.py, line 229 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgOSD98RTTNpVnvkDo:-Mt4Nes68h5DEt_mLKSt:bytb6y1) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L229)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

This sometimes causes problems if using multiprocessing spawn since each process re imports the files. We have an optional environment variable you can set to override the randomness, see base_dataset.py SceneContainer. 
</blockquote></details>

@chaofang-tri I made this small change. Please review.
___
*[dgp/datasets/agent_dataset.py, line 385 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgQIl85AKJGvv-1qoF:-Mt4Nk0Q-ujcHZt9MrFA:bv9kw2z) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L385)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

I think I missed it, but does this still work as intended if self.directory is None since directory is marked as optional in __init__.
</blockquote></details>

You're right. This shouldnt be optional in the docstring. Made the change.
___
*[dgp/datasets/agent_dataset.py, line 491 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgNQVtDI6hSihsA2YU:-Mt4NtnTCqGhjFDJFVni:b-dslkx1) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L491)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

not sure if it would be possible to expose the rest of the parameters for synchronized scene dataset? such as use_diskcache, accumulation etc.
</blockquote></details>

@chaofang-tri , is there a reason this wasnt included in the ouroboros version?
___
*[dgp/datasets/agent_dataset.py, line 491 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgRadr3Bhuhc1pFs8C:-Mt4O0Tw5kaDmdbviCpi:b-32k5t4) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L491)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

also, not sure if it makes sense, but can ParallelDomainSceneDataset be used here also? Have we tried converting a pd scene to agent format? If we think it would work it might be nice to make this underlying dataset user configurable, maybe a parameter like 'base_dataset_class' maybe.
</blockquote></details>

So, we havent tested with PD data.
___
*[dgp/datasets/agent_dataset.py, line 537 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgSHbz1W69ZAtPFtpG:-Mt4O5U1-gW2g1abf-ya:b116x3r) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L537)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

ditto. maybe a summary message or progress log IF this takes a while
</blockquote></details>

Added a very basic info, @chaofang-tri , any suggestions what would be best here?
___
*[dgp/datasets/agent_dataset.py, line 559 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgSUCG6wJUGGXVfm5C:-Mt4OCW0CkeGlCb-p0W3:b-a9ng06) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L559)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: how do you handle agents that have multiple births (i.e., someone who walks inside a store and then out, someone who enters a bus and then exits, an agent that is for some reason occluded for a long time etc)
</blockquote></details>

@chaofang-tri , I am actually not sure about this. Haven't come across scenarios where this happens, how do we handle?
___
*[dgp/datasets/agent_dataset.py, line 724 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgU6RW5KyggZqhS903:-Mt4OhmM7jbB1zCydQHM:b2nign6) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L724)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: is the 'main' agent ego? (what is a main agent?)
</blockquote></details>

yes
___
*[dgp/datasets/agent_dataset.py, line 728 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgTpdY-BUme5Jx37sB:-Mt4OfjuEsoiJX7dBWAm:b-8vdnqz) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L728)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: this seems like the output is going to be List[ dict[str, List ]  not List[ List[ dict]] as the docstring says?
</blockquote></details>

ill double check this.


<!-- Sent from Reviewable.io -->

2022-01-10 20:00 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 25 of 38 files reviewed, 18 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @visakii-work)

___
*[dgp/agents/agent_2d.py, line 19 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgJ7_h8yc3GuqxSADJ:-Mt4W7FZ2TipHSPlTYHD:bfprdfz) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L19)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: does it make sense to support BoundingBox2dAnnotationList?
</blockquote></details>

AgentSnapshot2DList is more general container than BoundingBox2dAnnotationList.



_Code quote:_
```Python
AgentSnapshot2DList(A
```
___
*[dgp/agents/base_agent.py, line 8 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgMALA3IuWwxy8bqF6:-Mt4WWqrD0WIrpYFuFFB:b9a9rcu) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/base_agent.py#L8)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

I think the reason was that future agents would be limited. @chaofang-tri ?
</blockquote></details>

Agree with @visakii-work , we want to make the base container more general.
___
*[dgp/datasets/agent_dataset.py, line 229 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgOSD98RTTNpVnvkDo:-Mt4XByt0RrEqjKMP76_:bh6t2rq) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L229)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

@chaofang-tri I made this small change. Please review.
</blockquote></details>

@visakii-work Please follow env way suggested by @chrisochoatri 
___
*[dgp/datasets/agent_dataset.py, line 491 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgRadr3Bhuhc1pFs8C:-Mt4XkSx8gMB4PaxXYFZ:bnedfxf) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L491)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

So, we havent tested with PD data.
</blockquote></details>

Add a todo here to support PD dataset @visakii-work 
___
*[dgp/datasets/agent_dataset.py, line 491 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgNQVtDI6hSihsA2YU:-Mt4Xtdc8PLqP5kmt1rR:bjf43an) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L491)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

@chaofang-tri , is there a reason this wasnt included in the ouroboros version?
</blockquote></details>

So far, we only expose the datums, the rest are not exposed until there is a use case.
___
*[dgp/datasets/agent_dataset.py, line 532 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgRUj98NBgeWEKwXlh:-Mt4YGvw6VE2WLw8Uloc:b7b4p6m) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L532)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

for some of these index building steps that can take a while, would be nice to have a logging.info or debug message every now and then
</blockquote></details>

@visakii-work Add some logging on index building if currently not added.
___
*[dgp/datasets/agent_dataset.py, line 537 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgSHbz1W69ZAtPFtpG:-Mt4YFMADzSpY-xi3_GQ:bb3dilr) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L537)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

Added a very basic info, @chaofang-tri , any suggestions what would be best here?
</blockquote></details>

Should be fine
___
*[dgp/datasets/agent_dataset.py, line 559 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgSUCG6wJUGGXVfm5C:-Mt4PeP37SG33o_6Be-o:bk5o7v9) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L559)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

@chaofang-tri , I am actually not sure about this. Haven't come across scenarios where this happens, how do we handle?
</blockquote></details>

the same agent shall have consistent  
___
*[dgp/datasets/agent_dataset.py, line 663 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgTOCM4yNg8zugBeC8:-Mt4Zp8A-tDrMzjNrvvq:bso7ixo) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L663)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

can you add datum_type as a key to be consistent with synchronzed scene?
</blockquote></details>

datum type is part of datum_data
___
*[dgp/datasets/agent_dataset.py, line 724 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgU6RW5KyggZqhS903:-Mt4YgL7-JlHFBMk71Gh:b-m0arl5) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L724)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

yes
</blockquote></details>

the main agent is the agent from agent index. The is kind of strange but requested by Trajectron++


<!-- Sent from Reviewable.io -->

2022-01-11 20:32 UTC, chrisochoatri requested changes
> Reviewed 2 of 13 files at r8.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 27 of 38 files reviewed, 9 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @visakii-work)

___
*[dgp/datasets/agent_dataset.py, line 663 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgTOCM4yNg8zugBeC8:-Mt9nMBw6RlJtvp4qycy:b-dlk3uj) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L663)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

datum type is part of datum_data
</blockquote></details>

so are rgb and timestamp, I'm suggesting that datum_data be listed below along with the other keys. or is the docstring out of date?
___
*[dgp/datasets/base_dataset.py, line 171 at r11](https://reviewable.io/reviews/tri-ml/dgp/67#-Mt9npTrBGmX-TxIVtte:-Mt9npTrBGmX-TxIVttf:b-pedm92) ([raw file](https://github.com/tri-ml/dgp/blob/51c11bfa200cf45b63e83d0bc0a73fe45ad7208e/dgp/datasets/base_dataset.py#L171)):*
> ```Python
>         """Get datum type based on the datum name"""
>         for datum in self.data:
>             if datum.id.name.lower() == datum_name:
> ```

I think if you do a .lower on one side you should do a .lower on the other side also.



_Code quote:_
```Python
datum_name
```
___
*[dgp/utils/protobuf.py, line 157 at r11](https://reviewable.io/reviews/tri-ml/dgp/67#-Mt9p7O0-NsfvM65YceG:-Mt9p7O0-NsfvM65YceH:b-baxecl) ([raw file](https://github.com/tri-ml/dgp/blob/51c11bfa200cf45b63e83d0bc0a73fe45ad7208e/dgp/utils/protobuf.py#L157)):*
> ```Python
>             return ontology
>     except Exception:
>         logging.info('Failed to load ontology file.')
> ```

nit: might be nice to print the file name and maybe logging.error instead? up to you.



_Code quote:_
```Python
logging.info('Failed to load ontology file.')
```
___
*[dgp/utils/protobuf.py, line 186 at r11](https://reviewable.io/reviews/tri-ml/dgp/67#-Mt9pKd4EMYjzu5FQSqj:-Mt9pKd4EMYjzu5FQSqk:b-qf55jr) ([raw file](https://github.com/tri-ml/dgp/blob/51c11bfa200cf45b63e83d0bc0a73fe45ad7208e/dgp/utils/protobuf.py#L186)):*
> ```Python
> 
> def get_latest_scene(s3_scene_jsons):
>     '''From a list of 'scene.json' and/or 'scene_<sha1>.json' paths in s3,
> ```

nit: """ for consistency



_Code quote:_
```Python
'''
```


<!-- Sent from Reviewable.io -->

2022-01-11 23:19 UTC, chrisochoatri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 27 of 38 files reviewed, 9 unresolved discussions (waiting on @chao, @ChaoFang-TRI, @chrisochoatri, and @visakii-work)

___
*[dgp/agents/agent_2d.py, line 19 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgJ7_h8yc3GuqxSADJ:-MtAQF4E3g3WED3QxM5-:b-o2yt2) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L19)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

AgentSnapshot2DList is more general container than BoundingBox2dAnnotationList.
</blockquote></details>

I meant as an argument to init. We take boxlist, should we allow BoundingBox2dAnnotationList
___
*[dgp/datasets/agent_dataset.py, line 559 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgSUCG6wJUGGXVfm5C:-MtAQgUN2HUFx4bwSzIw:boo0o85) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L559)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

the same agent shall have consistent  
</blockquote></details>

not sure what you mean @chao. In driving there must certainly be support for re-identifying a lost track. My question is how do you handle these scenarios.


<!-- Sent from Reviewable.io -->

2022-01-12 20:44 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 27 of 38 files reviewed, 7 unresolved discussions (waiting on @chao, @ChaoFang-TRI, @chrisochoatri, and @visakii-work)

___
*[dgp/datasets/agent_dataset.py, line 559 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgSUCG6wJUGGXVfm5C:-MtF0yWT2kXA1iKCyJ8x:b-xh4mau) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L559)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

not sure what you mean @chao. In driving there must certainly be support for re-identifying a lost track. My question is how do you handle these scenarios.
</blockquote></details>

@chaofang-tri , could you please elaborate?
___
*[dgp/datasets/agent_dataset.py, line 663 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgTOCM4yNg8zugBeC8:-MtF0uGAA_MZqFx1Fa1q:b-tzjntn) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L663)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

so are rgb and timestamp, I'm suggesting that datum_data be listed below along with the other keys. or is the docstring out of date?
</blockquote></details>

@chaofang-tri thoughts?
___
*[dgp/datasets/agent_dataset.py, line 728 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgTpdY-BUme5Jx37sB:-MtF0rLs0McYclMEsfkc:bdy08ll) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L728)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

ill double check this.
</blockquote></details>

fixed the docstring
___
*[dgp/datasets/base_dataset.py, line 171 at r11](https://reviewable.io/reviews/tri-ml/dgp/67#-Mt9npTrBGmX-TxIVtte:-MtF0pczA5AupYPux5Nc:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/51c11bfa200cf45b63e83d0bc0a73fe45ad7208e/dgp/datasets/base_dataset.py#L171)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

I think if you do a .lower on one side you should do a .lower on the other side also.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-12 23:07 UTC, chrisochoatri reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> just want to have some closure on those last few items in case they are (unlikely) important.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67#-:-MtFXgb044pXnclVFlkE:b-5wkqom)* status: 27 of 38 files reviewed, 5 unresolved discussions (waiting on @chao, @ChaoFang-TRI, @chrisochoatri, and @visakii-work)



<!-- Sent from Reviewable.io -->

2022-01-13 00:52 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 27 of 38 files reviewed, 5 unresolved discussions (waiting on @chao, @ChaoFang-TRI, @chrisochoatri, and @visakii-work)

___
*[dgp/agents/agent_2d.py, line 19 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgJ7_h8yc3GuqxSADJ:-MtFFrMW7lrD_7dGoCYp:b4hlmh8) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/agents/agent_2d.py#L19)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

I meant as an argument to init. We take boxlist, should we allow BoundingBox2dAnnotationList
</blockquote></details>

I see, currently, there is no use case to support BoundingBox2dAnnotationList, this class is to load data from BoundingBox2D directly, we could put a TODO here to support BoundingBox2dAnnotationList. @visakii-work 
___
*[dgp/datasets/agent_dataset.py, line 559 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgSUCG6wJUGGXVfm5C:-MtFGoCT0iiAB9ch2psk:bmezs3p) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L559)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

@chaofang-tri , could you please elaborate?
</blockquote></details>

I think it is legacy logic from trajectron dataset to only use continuous tracks. 
___
*[dgp/datasets/agent_dataset.py, line 663 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgTOCM4yNg8zugBeC8:-MtFuoUuDphp2vBd9mFF:b-9lmsmh) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L663)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

@chaofang-tri thoughts?
</blockquote></details>

@visakii-work the doc string seems out of date


<!-- Sent from Reviewable.io -->

2022-01-13 18:17 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 27 of 38 files reviewed, 2 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @visakii-work)

___
*[dgp/datasets/agent_dataset.py, line 663 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgTOCM4yNg8zugBeC8:-MtJdx_3-_AJN90hNDM0:bq5wann) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L663)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

@visakii-work the doc string seems out of date
</blockquote></details>


@chaofang-tri , @chrisochoatri made a few changes to the docstring, does this make more sense? 


<!-- Sent from Reviewable.io -->

2022-01-13 18:40 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 27 of 38 files reviewed, 4 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @visakii-work)

___
*[dgp/datasets/agent_dataset.py, line 452 at r7](https://reviewable.io/reviews/tri-ml/dgp/67#-MsgNYbY2nXXeJYeztva:-MtJg4ce9WVAi0t3U2k9:b-4tm9dg) ([raw file](https://github.com/tri-ml/dgp/blob/31caeed906281f0ba0edcd1c96079ac0f7087292/dgp/datasets/agent_dataset.py#L452)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

can you add use_diskcache as an option?
</blockquote></details>

Added use_diskcache. its only used with SynchronizedScenedataset though.


<!-- Sent from Reviewable.io -->

2022-01-13 18:45 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 27 of 38 files reviewed, 4 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @visakii-work)

___
*[dgp/datasets/agent_dataset.py, line 669 at r13](https://reviewable.io/reviews/tri-ml/dgp/67#-MtJiVm38FEDnAsYZF0A:-MtJkSQpCIqquYhUQBbW:b-qssebl) ([raw file](https://github.com/tri-ml/dgp/blob/b2f2df30b5a20b7c1a44db9cd6b5b67f0205deea/dgp/datasets/agent_dataset.py#L669)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

fixed.


<!-- Sent from Reviewable.io -->

2022-01-13 18:47 UTC, visakii-work reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: 27 of 38 files reviewed, 4 unresolved discussions (waiting on @ChaoFang-TRI and @chrisochoatri)

___
*[dgp/datasets/agent_dataset.py, line 911 at r13](https://reviewable.io/reviews/tri-ml/dgp/67#-MtJiY0QC2HhNTNrgXsu:-MtJks260Ir-vpzUo4bk:b-igpo9k) ([raw file](https://github.com/tri-ml/dgp/blob/b2f2df30b5a20b7c1a44db9cd6b5b67f0205deea/dgp/datasets/agent_dataset.py#L911)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

white space. (sorry!)
</blockquote></details>

fixed , sorrry!!


<!-- Sent from Reviewable.io -->

2022-01-13 19:05 UTC, chrisochoatri approved these changes
> Reviewed 2 of 38 files at r1, 6 of 24 files at r4, 1 of 6 files at r5, 7 of 13 files at r8, 2 of 3 files at r12, 1 of 2 files at r13, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @visakii-work)



<!-- Sent from Reviewable.io -->

2022-01-14 17:16 UTC, merged