schema: add map proto
TRI-ML/dgp pull request #70
Opened 2021-12-13 20:00 UTC by ChaoFang-TRI

- Add map.proto file which contains map schema
- Add trafficlightstate as datum in sample.proto

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tri-ml/dgp/70)

2021-12-13 20:00 UTC, ChaoFang-TRI reviewed
FYI @kuanleetri @visakii-work @chrisochoatri 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MqpNRwd1RVrX7fMBgCb:bvqhmqn)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2021-12-13 21:22 UTC, quincy-kh-chen requested changes
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: 3 of 5 files reviewed, 27 unresolved discussions (waiting on @ChaoFang-TRI)

___
*[dgp/proto/map.proto, line 14 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpakZ94t6_5slYmBSP:-MqpakZ94t6_5slYmBSQ:bncx11x) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L14)):*
> ```protobuf
> 
> // Coordinates on the map.
> message Point3D{
> ```

IMO to keep consistency, this structure should be under (https://github.com/TRI-ML/dgp/blob/master/dgp/proto/annotations.proto) along with other structures.
___
*[dgp/proto/map.proto, line 21 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpaueO1L03-S_qn3pN:-MqpaueO1L03-S_qn3pO:b-fjwak9) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L21)):*
> ```protobuf
> 
> // Basic container for line divider on road, contains sequence of points to form a polyline.
> message LineDivider{
> ```

LaneDivider or LaneBoundary or LaneLine?
___
*[dgp/proto/map.proto, line 22 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpb4hBD0MLqr-XvP4f:-Mqpb4hBD0MLqr-XvP4g:buoxv1r) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L22)):*
> ```protobuf
> // Basic container for line divider on road, contains sequence of points to form a polyline.
> message LineDivider{
>     // List of points to form a continuous line.
> ```

Are these points required to be ordered? If so, what order it should follow? We should document this.
___
*[dgp/proto/map.proto, line 23 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbCNcEvf53tHK9QbE:-MqpbCNd2P8UJeYYOL-h:b-4vsoii) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L23)):*
> ```protobuf
> message LineDivider{
>     // List of points to form a continuous line.
>     repeated Point3D way_points = 1;
> ```

Do we have a better name than `way_points`? Why not just `points`?
___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-MqpbOT14HMt9f_jh2DN:b-3iwtjo) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
> ```protobuf
> 
>     // Enum of types of the line divider.
>     enum DividerType {
> ```

Looks to me we should split this into multiple "LaneLine Attributes" instead of flattening it. Otherwise we will have infinite amount of enumerations in the future if we want to include more color, type, material, etc.
For example, `color` (WHITE, YELLOW, RED, BLUE, etc), `type` (SINGLE_SOLID, DOUBLE SOLID, SINGLE_DASHED, DOUBLE DASHED, TRIPLE DASHED, CURB, etc), `material` (PAINT, etc)  
___
*[dgp/proto/map.proto, line 47 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpcQi4AxzQ0Jf4weHb:-MqpcQi4AxzQ0Jf4weHc:b-k4ujqa) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L47)):*
> ```protobuf
> 
> // Defines lane information - centerline, boundaries, etc.
> message Lane {
> ```

Let's also define what's a "lane"? 
i.e. to answer some questions such as does a lane include two-way traffic or just one-way traffic
___
*[dgp/proto/map.proto, line 52 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpcKEo3dvQJeNCYnMv:-MqpcKEo3dvQJeNCYnMw:bk3743t) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L52)):*
> ```protobuf
> 
>   // List of center line segments.
>   LineDivider center_line = 2;
> ```

What's the definition of center_line? 
___
*[dgp/proto/map.proto, line 55 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpcm-t7qDnRT8ZcaAu:-Mqpcj4_4BvM8XcwR2i-:b-curopg) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L55)):*
> ```
> f
> ```
Does a lane always have `left_lane_boundary`?
___
*[dgp/proto/map.proto, line 58 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpcpOSAneHs6FtNJ-E:-MqpcpOSAneHs6FtNJ-F:bt9rkk3) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L58)):*
> ```protobuf
> 
>   // Right lane boundary.
>   LineDivider right_lane_boundary = 4;
> ```

Does a lane always have `right_lane_boundary`?
___
*[dgp/proto/map.proto, line 61 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpcvIR55qdDcmv8kAG:-MqpcvIR55qdDcmv8kAH:b-9gfc21) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L61)):*
> ```protobuf
> }
> 
> // The geometry of the edges of zone, represented as a chain of polylines to form a polygon.
> ```

Can we elaborate what's a "zone"? To provide some example such as crosswalk?
___
*[dgp/proto/map.proto, line 63 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpd1RQ6AGswdG543kr:-Mqpd1RQ6AGswdG543ks:ber7h37) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L63)):*
> ```protobuf
> // The geometry of the edges of zone, represented as a chain of polylines to form a polygon.
> message Boundary{
>   // List of edge of boundary polygon.
> ```

Do these edges have to be ordered? If so, what order we should follow?
___
*[dgp/proto/map.proto, line 68 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpdLSh4rhl8VMKYZF2:-MqpdLSi-r1ZvaJdLLgo:b-9gfc21) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L68)):*
> ```protobuf
> 
> // Defines zone information.
> message Zone {
> ```

Can we elaborate what's a "zone"? To provide some example such as crosswalk?
___
*[dgp/proto/map.proto, line 75 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpdBHP5KdVc7aNZdiv:-MqpdBHP5KdVc7aNZdiw:b-6az48c) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L75)):*
> ```protobuf
>   string type = 2;
> 
>   // Note: the polygon can be a polyline.
> ```

What's the difference between polygon and polyline we define here? 
___
*[dgp/proto/map.proto, line 80 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpdOz53ZXE5mBaYlCm:-MqpdOz53ZXE5mBaYlCn:bcvyuok) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L80)):*
> ```
> LocalMapView
> ```
What's the intuition behind this naming convention (assuming we want to make this generic instead of TRI specific).
___
*[dgp/proto/map.proto, line 82 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpdi2WAA7uy1qpBCv-:-Mqpdi2WAA7uy1qpBCv0:b-ltvifg) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L82)):*
> ```protobuf
> message LocalMapView {
>   // List of Lanes in the map.
>   repeated Lane lanes = 1;
> ```

Do these lanes have to be ordered? If so, what order we should follow?
___
*[dgp/proto/map.proto, line 85 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpdjz9E4gMPVATLsJo:-Mqpdjz9E4gMPVATLsJp:bfj0awk) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L85)):*
> ```protobuf
> 
>   // List of zones, such as crosswalk regions, intersections.
>   repeated Zone zones = 2;
> ```

Do these zones have to be ordered? If so, what order we should follow?
___
*[dgp/proto/map.proto, line 88 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpdm-5AqwVZCKevjt-:-Mqpdm-5AqwVZCKevjt0:be0rdbx) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L88)):*
> ```protobuf
> 
>   // An id to store reference to map files and position in them.
>   string external_map_id = 3;
> ```

Please elaborate the use cases.
___
*[dgp/proto/map.proto, line 94 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpdqUD96ENEaR3MmS0:-Mqp [...]

2021-12-13 21:23 UTC, quincy-kh-chen reviewed
Personally I'd suggest putting this under contrib folder as this PR looks a bit specific to TRI's mapping schema.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MqpfI0h-ptM7ahsIoxv:b-okwlwl)* status: 3 of 5 files reviewed, 27 unresolved discussions (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2021-12-14 21:06 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: 3 of 5 files reviewed, 27 unresolved discussions (waiting on @ChaoFang-TRI and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 14 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpakZ94t6_5slYmBSP:-MquT0HQDh1gMSfmt3qK:bo1enel) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L14)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

IMO to keep consistency, this structure should be under (https://github.com/TRI-ML/dgp/blob/master/dgp/proto/annotations.proto) along with other structures.
</blockquote></details>

It would be strange for map proto to depend on annotaion proto. Move it to geometry.proto
___
*[dgp/proto/map.proto, line 21 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpaueO1L03-S_qn3pN:-MquTvdM2hcKL9oo1TLf:by1ap2h) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L21)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

LaneDivider or LaneBoundary or LaneLine?
</blockquote></details>

Rename to LaneDivider.
___
*[dgp/proto/map.proto, line 22 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpb4hBD0MLqr-XvP4f:-MquZpgC1hMXHqNid2bk:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L22)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Are these points required to be ordered? If so, what order it should follow? We should document this.
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 23 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbCNcEvf53tHK9QbE:-MquZqneDCw5VaZZ2wi2:b-w9edd7) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L23)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Do we have a better name than `way_points`? Why not just `points`?
</blockquote></details>

way_points are common name in map
___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-MquZz6B56Wda1S-MhIU:b-nr7pxr) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Looks to me we should split this into multiple "LaneLine Attributes" instead of flattening it. Otherwise we will have infinite amount of enumerations in the future if we want to include more color, type, material, etc.
For example, `color` (WHITE, YELLOW, RED, BLUE, etc), `type` (SINGLE_SOLID, DOUBLE SOLID, SINGLE_DASHED, DOUBLE DASHED, TRIPLE DASHED, CURB, etc), `material` (PAINT, etc)  
</blockquote></details>

This part is aligned with L5 map proto. I agree it is less configurable.
___
*[dgp/proto/map.proto, line 47 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpcQi4AxzQ0Jf4weHb:-Mqua3ry-PyNoRoFSmfn:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L47)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Let's also define what's a "lane"? 
i.e. to answer some questions such as does a lane include two-way traffic or just one-way traffic
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 52 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpcKEo3dvQJeNCYnMv:-MquaPY68HDvhErqr5rH:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L52)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

What's the definition of center_line? 
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 55 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpcm-t7qDnRT8ZcaAu:-MquaR1HEG2yI8daMWxf:b2nign6) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L55)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> f
> ```
Does a lane always have `left_lane_boundary`?
</blockquote></details>

yes
___
*[dgp/proto/map.proto, line 58 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpcpOSAneHs6FtNJ-E:-MquaTXj-QnAHDDcTIiw:b2nign6) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L58)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Does a lane always have `right_lane_boundary`?
</blockquote></details>

yes
___
*[dgp/proto/map.proto, line 61 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpcvIR55qdDcmv8kAG:-MqubLBKAiGw8q4A6WY5:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L61)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Can we elaborate what's a "zone"? To provide some example such as crosswalk?
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 63 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpd1RQ6AGswdG543kr:-Mqubd6d7JZiQui2krtn:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L63)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Do these edges have to be ordered? If so, what order we should follow?
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 68 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpdLSh4rhl8VMKYZF2:-MqubeDd8ThX0T2ukEkb:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L68)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Can we elaborate what's a "zone"? To provide some example such as crosswalk?
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 75 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpdBHP5KdVc7aNZdiv:-Mquc54p9xyO5sQUgsyC:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L75)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

What's the difference between polygon and polyline we define here? 
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 80 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpdOz53ZXE5mBaYlCm:-MqufsaN01rmM56TXclO:bquhj8o) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L80)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> LocalMapView
> ```
What's the intuition behind this naming convention (assuming we want to make this generic instead of TRI specific).
</blockquote></details>

Changed name to be more generic
___
*[dgp/proto/map.proto, line 82 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpdi2WAA7uy1qpBCv-:-Mqufqeb4FAA7ZKn6EHG:b-yv1csl) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L82)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Do these lanes have to be ordered? If so, what order we should follow?
</blockquote></details>

not ordered
___
*[dgp/proto/map.proto, line 85 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpdjz9E4gMPVATLsJo:-Mqufocn6d1J7ZCzXozx:box6os9) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L85)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Do [...]

2021-12-16 00:19 UTC, ChaoFang-TRI reviewed
The map schema is not TRI specific so I recommend to put it in schema folder. We intent to grow it into standard DGP map schema with more use cases.  

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-Mr-_Qht4lJ9iRFlM4cM:b-ntt3ks)* status: 1 of 7 files reviewed, 27 unresolved discussions (waiting on @ChaoFang-TRI and @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2021-12-16 02:18 UTC, chrisochoatri reviewed
+@chrisochoatri review

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-Mr01-DZAvS6ad-cArSo:b-ypyw24)* status: 1 of 7 files reviewed, 27 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2021-12-16 02:32 UTC, kuanleetri requested changes
finish the first run

> Reviewed 4 of 5 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-Mr04GmP9NU7yqr8OV8V:b-usjn6k)* status: 6 of 7 files reviewed, 28 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @quincy-kh-chen)

___
*[dgp/proto/geometry.proto, line 9 at r2](https://reviewable.io/reviews/tri-ml/dgp/70#-Mr00Jqw4ej9M1c4WY0-:-Mr00Jqx2k7jYG3qIy6s:bvh20sf) ([raw file](https://github.com/tri-ml/dgp/blob/3ace99dae0b20614d89b2e1ee1572b1b0de8eeef/dgp/proto/geometry.proto#L9)):*
> ```protobuf
> 
> // Coordinates on the map.
> message Point3D{
> ```

Can `Vector3` be used for this?
___
*[dgp/proto/map.proto, line 23 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbCNcEvf53tHK9QbE:-Mr02sjz0hImkcP8C62V:b-9je843) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L23)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

way_points are common name in map
</blockquote></details>

way_points is common +1
___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-Mqr2xI35-8n4HjzUU66:bdb1orw) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

This part is aligned with L5 map proto. I agree it is less configurable.
</blockquote></details>

I'm leaning on the attribute idea for generalization.
___
*[dgp/proto/sample.proto, line 37 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpf1SE2vQczlog1D5i:-Mqr0IYp1DRhHthXyaxR:b35djsa) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/sample.proto#L37)):*
> ```
> traffic_light_stata
> ```
typo? also want to know this `TrafficLightState` is dynamic or fixed in a map.
I wonder if we can have a message to include map stuff, as we want to treat map as datum
Like `MapDatum map_datum` thoughts?


<!-- Sent from Reviewable.io -->

2021-12-16 15:34 UTC, kuanleetri reviewed
it'd be better to have a ascii figure to explain the elements.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-Mr2sCnq0_1cxbxLKLFl:b-lgf5dd)* status: 6 of 7 files reviewed, 28 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2021-12-17 01:29 UTC, chrisochoatri requested changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: 6 of 7 files reviewed, 29 unresolved discussions (waiting on @ChaoFang-TRI and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 14 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpakZ94t6_5slYmBSP:-Mr4x7QZDU1gSAtMcGlg:bo1vs2w) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L14)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

It would be strange for map proto to depend on annotaion proto. Move it to geometry.proto
</blockquote></details>

no strong opinions here, but it could be argued all of these messages: lanes, lane dividers etc should/could be implemented as annotations that re use our existing geometric primitives and annotations.
___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-Mr4xeMz9kIxSws4kV4v:bsbsd8u) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

I'm leaning on the attribute idea for generalization.
</blockquote></details>

nit: this looks like an ontology to me, did we consider viewing map metadata as an annotation? map as a datum?
___
*[dgp/proto/map.proto, line 105 at r2](https://reviewable.io/reviews/tri-ml/dgp/70#-Mr4yc0WDQGnwsHvT4_v:-Mr4yc0WDQGnwsHvT4_w:b-to6pcp) ([raw file](https://github.com/tri-ml/dgp/blob/3ace99dae0b20614d89b2e1ee1572b1b0de8eeef/dgp/proto/map.proto#L105)):*
> ```protobuf
> 
>   // Pose of this sample from
>   Pose pose = 2;
> ```

Why not add this to sample instead?
___
*[dgp/proto/sample.proto, line 37 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpf1SE2vQczlog1D5i:-Mr5-E0S1VXUBZRbXsLq:b-61225t) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/sample.proto#L37)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

> ```
> traffic_light_stata
> ```
typo? also want to know this `TrafficLightState` is dynamic or fixed in a map.
I wonder if we can have a message to include map stuff, as we want to treat map as datum
Like `MapDatum map_datum` thoughts?
</blockquote></details>

I agree with Quincy here. I think also map should be a datum, and all of these things like lanes, dividers, stop signs etc should be annotations. Someone literally has to annotate a map to get them. 


<!-- Sent from Reviewable.io -->

2021-12-17 01:49 UTC, chrisochoatri reviewed
Nice work Chao, this adds a lot of stuff. I don't feel I understand the use case well enough to provide good feedback. Might be nice to hear from some of the PAC folks. 

My two cents are this is a very different format than what we currently have and it might be nice to try and make it more similar to the sample/datum/annotation/geometry setup we already use.

My other thought is that I would really like to see the global pose transforms added to sample or scene and keep map elements relative to ego or the current static coordinate system. This has some advantages in that it 1.) We get access to global pose for other uses with almost no changes to existing dataloaders and 2) Guang shared a file with data privacy guidelines and we need to make sure we can easily mask the global pose from any dataset that might be shared. This would be easy to do if the map elements are relative to ego or scene global and you can still render everything.  

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-Mr52H5B1-xljagl1iJS:b-t1sv7)* status: 6 of 7 files reviewed, 29 unresolved discussions (waiting on @ChaoFang-TRI and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 123 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpeP0l-OER1gkTYRL_:-Mr50gOv78E7j8y0kFQr:b8kwpuf) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L123)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

I think the comments are clear, it is to aasociate TL and a lane
</blockquote></details>

is it always a 1-1 match between traffic lights and lanes?
___
*[dgp/proto/map.proto, line 129 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpeT_GApL7A-wbvX3R:-Mr51gOuAkVXqJwTdin1:b-dci89w) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L129)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

it is quite flexible for porting other maps with key and value
</blockquote></details>

can you elaborate a bit more, also curious about this


<!-- Sent from Reviewable.io -->

2021-12-17 18:19 UTC, ChaoFang-TRI reviewed
@chrisochoatri Agree to have global pose added to sample, but currently, the only use case is for map. Change of sample proto would need one time update of all dataset which I think we need to revisit later. I think we also need to add traffic light status to sample as well. 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-Mr8a38u3ZorEveU4EIO:b-3kj33c)* status: 5 of 7 files reviewed, 29 unresolved discussions (waiting on @chrisochoatri, @kuanleetri, and @quincy-kh-chen)

___
*[dgp/proto/geometry.proto, line 9 at r2](https://reviewable.io/reviews/tri-ml/dgp/70#-Mr00Jqw4ej9M1c4WY0-:-Mr16AxN9wemzOWytWPy:b7shgii) ([raw file](https://github.com/tri-ml/dgp/blob/3ace99dae0b20614d89b2e1ee1572b1b0de8eeef/dgp/proto/geometry.proto#L9)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

Can `Vector3` be used for this?
</blockquote></details>

vector3 is for translation vector of SE3, Point3 is a poind in 3D space, totally different. Though the underlining low level data type are the same.
___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-Mr8WZ7m7iipWdwxQ4-t:b3p529k) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: this looks like an ontology to me, did we consider viewing map metadata as an annotation? map as a datum?
</blockquote></details>

@chrisochoatri It is true map is a form of annotation and it is an annotation of the scene. Current datum are on sample level so it is too large extension to make map a datum. Also, there are code duplication issue. We just create the map message to since it is special.

@kuanleetri @quincy-kh-chen Update to use attributes.
___
*[dgp/proto/map.proto, line 123 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpeP0l-OER1gkTYRL_:-Mr8bK-dB12NIeFMw3Wl:b-mcnd0n) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L123)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

is it always a 1-1 match between traffic lights and lanes?
</blockquote></details>

Not necessary. There shall be multiple TLS message in sample.
___
*[dgp/proto/map.proto, line 105 at r2](https://reviewable.io/reviews/tri-ml/dgp/70#-Mr4yc0WDQGnwsHvT4_v:-Mr8ajl16fWnDfAQO4Kq:bciz0) ([raw file](https://github.com/tri-ml/dgp/blob/3ace99dae0b20614d89b2e1ee1572b1b0de8eeef/dgp/proto/map.proto#L105)):*
> dataset
The change of scope is much larger to modify sample proto. It is beyond the scope of this PR.


<!-- Sent from Reviewable.io -->

2021-12-18 01:10 UTC, chrisochoatri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: 5 of 7 files reviewed, 28 unresolved discussions (waiting on @kuanleetri and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 123 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpeP0l-OER1gkTYRL_:-MrA4MudChIXtXLAzjSo:bqqhvj7) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L123)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

Not necessary. There shall be multiple TLS message in sample.
</blockquote></details>

so if there are two lanes and one traffic light, we would have two identical TLS messages that differ only in map_element_id_from? 


<!-- Sent from Reviewable.io -->

2021-12-20 18:11 UTC, chrisochoatri reviewed
I see, thanks. 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MrO1EMG-RzrFtSckj5Q:b-6xeinu)* status: 5 of 7 files reviewed, 28 unresolved discussions (waiting on @kuanleetri and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-MrO1N1t9n3MVwOJwVNg:bcsym3n) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

@chrisochoatri It is true map is a form of annotation and it is an annotation of the scene. Current datum are on sample level so it is too large extension to make map a datum. Also, there are code duplication issue. We just create the map message to since it is special.

@kuanleetri @quincy-kh-chen Update to use attributes.
</blockquote></details>

makes sense, thanks.


<!-- Sent from Reviewable.io -->

2021-12-20 21:31 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: 5 of 7 files reviewed, 28 unresolved discussions (waiting on @kuanleetri and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 123 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpeP0l-OER1gkTYRL_:-MrOkM7n5yWfQX-UahB2:b2nign6) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L123)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

so if there are two lanes and one traffic light, we would have two identical TLS messages that differ only in map_element_id_from? 
</blockquote></details>

yes
___
*[dgp/proto/map.proto, line 129 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpeT_GApL7A-wbvX3R:-MrOkOxy04tDwGc8Lgzj:bptjetg) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L129)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

can you elaborate a bit more, also curious about this
</blockquote></details>

some map use id:state pair


<!-- Sent from Reviewable.io -->

2021-12-20 21:54 UTC, chrisochoatri reviewed
@chaofang-tri by any chance do you have a diagram that shows how the protos interconnect? something like https://github.com/TRI-ML/dgp/blob/master/docs/scene-dataset-schema.jpg. Might make it easier to discuss.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MrOovjHCOGvrVLyHMLs:b-3lc7dj)* status: 5 of 7 files reviewed, 28 unresolved discussions (waiting on @kuanleetri and @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2022-01-04 19:43 UTC, quincy-kh-chen requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: 5 of 7 files reviewed, 18 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @kuanleetri, and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-MsaYfvc7ZuVTp-LeBDt:btfte8l) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

makes sense, thanks.
</blockquote></details>

BTW what's the difference between `UNKNOWN` and `None`? Shall we just collapse these 2 categories into `UNKNOWN`?
___
*[dgp/proto/map.proto, line 88 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpdm-5AqwVZCKevjt-:-Msaar9ECuCpRBCnXbW9:b-jr0v28) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L88)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

refer to tlog map id.
</blockquote></details>

BTW why don't we put this into the filed `google.protobuf.Any map_data = 4`
___
*[dgp/proto/map.proto, line 98 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpdvUb20c_0mFCUoVG:-Msab3BX74D5aWRDtIB0:b-9ua0wn) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L98)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW we can elaborate this as `Earth-centered Earth-fixed coordinate`
___
*[dgp/proto/map.proto, line 42 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaYYsJAGMhT2T7g2Mq:-MsaYYsJAGMhT2T7g2Mr:b-1vtp5o) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L42)):*
> ```protobuf
>    // Enum of material of the lane divider.
>   enum LaneDividerMaterial {
>     UNCLEAR = 0;
> ```

Suggest renaming `UNCLEAR` to `UNKNOWN` for consistency.
___
*[dgp/proto/map.proto, line 46 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaYwIa-Mo0qmCmWQ0L:-MsaYwIa-Mo0qmCmWQ0M:bf04z6k) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L46)):*
> ```protobuf
>   }
> 
>   // Type of lane divider.
> ```

BTW let's just the original message name `LaneDivider`



_Code quote:_
```protobuf
lane divider
```
___
*[dgp/proto/map.proto, line 47 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaZC2y2JMRJUVGtBCJ:-MsaZC2y2JMRJUVGtBCK:b-ik0zu6) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L47)):*
> ```protobuf
> 
>   // Type of lane divider.
>   LaneDividerType divider_type = 2;
> ```

`type` for simplicity?



_Code quote:_
```protobuf
divider_type
```
___
*[dgp/proto/map.proto, line 49 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaZ7aTEuVyhRWvgw5l:-MsaZ7aTEuVyhRWvgw5m:bf04z6k) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L49)):*
> ```protobuf
>   LaneDividerType divider_type = 2;
> 
>   // Color of lane divider.
> ```

BTW let's just the original message name `LaneDivider`



_Code quote:_
```protobuf
lane divider
```
___
*[dgp/proto/map.proto, line 50 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaZEdlCqoV3pjXIjpA:-MsaZEdlCqoV3pjXIjpB:b-bd6opt) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L50)):*
> ```protobuf
> 
>   // Color of lane divider.
>   LaneDividerColor divider_color = 3;
> ```

`color` for simplicity?
___
*[dgp/proto/map.proto, line 52 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaZAXsEVmN-2oDBBXj:-MsaZAXsEVmN-2oDBBXk:bf04z6k) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L52)):*
> ```protobuf
>   LaneDividerColor divider_color = 3;
> 
>   // Material of lane divider.
> ```

BTW let's just the original message name `LaneDivider`



_Code quote:_
```protobuf
lane divider
```
___
*[dgp/proto/map.proto, line 53 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaZKc41_uFGPbH_55D:-MsaZKc41_uFGPbH_55E:bvwfxz9) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L53)):*
> ```protobuf
> 
>   // Material of lane divider.
>   LaneDividerMaterial divier_material = 4;
> ```

`material` for simplicity?
___
*[dgp/proto/map.proto, line 61 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-Msa__O77rZWhoh8W_9Q:-Msa__O77rZWhoh8W_9R:b-xma3oy) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L61)):*
> ```protobuf
>   string id = 1;
> 
>   // List of center line segments. It is geometrically the centers between left and right lane boundaries.
> ```

Not a list? Isn't this just a single centerline?



_Code quote:_
```protobuf
List
```
___
*[dgp/proto/map.proto, line 102 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaaPdW1b2ql7i3GOQQ:-MsaaPdW1b2ql7i3GOQR:bjvr6qz) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L102)):*
> ```protobuf
> message SceneMap {
>   // List of Lanes in the map.
>   repeated Lane lanes = 1;
> ```

BTW do we need to introduce the concept of `roadway`? i.e. a `roadway` consists of multiple `lane` in the same direction. 
___
*[dgp/proto/map.proto, line 121 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsabARLD--LjdzsgeUS:-MsabARLD--LjdzsgeUT:b-n4napi) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L121)):*
> ```protobuf
>   DatumId sample_id = 1;
> 
>   // Pose of this sample in ECEF.
> ```

BTW we can elaborate this as `Earth-centered Earth-fixed coordinate system.`


<!-- Sent from Reviewable.io -->

2022-01-15 00:03 UTC, chrisochoatri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: 5 of 7 files reviewed, 19 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, @kuanleetri, and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 22 at r4](https://reviewable.io/reviews/tri-ml/dgp/70#-MtQ0Lol5DBFYWVfI7jT:-MtQ0Lom-o_MjiAlqGgt:b-nyok8) ([raw file](https://github.com/tri-ml/dgp/blob/81428bcef88f88e76db7a6aaa9e9e7de70057acf/dgp/proto/map.proto#L22)):*
> ```protobuf
>     TYPE_UNKNOWN = 0;
>     TYPE_NONE = 1;
>     YPE_SINGLE_SOLID = 2;
> ```

typo: YPE -> TYPE



_Code quote:_
```protobuf
YPE
```


<!-- Sent from Reviewable.io -->

2022-01-19 02:33 UTC, kuanleetri requested changes
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: 6 of 7 files reviewed, 19 unresolved discussions (waiting on @ChaoFang-TRI, @chrisochoatri, and @quincy-kh-chen)

___
*[dgp/proto/geometry.proto, line 9 at r2](https://reviewable.io/reviews/tri-ml/dgp/70#-Mr00Jqw4ej9M1c4WY0-:-MrO8xeM2NtgW4E8WX_8:b-a4pc39) ([raw file](https://github.com/tri-ml/dgp/blob/3ace99dae0b20614d89b2e1ee1572b1b0de8eeef/dgp/proto/geometry.proto#L9)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

vector3 is for translation vector of SE3, Point3 is a poind in 3D space, totally different. Though the underlining low level data type are the same.
</blockquote></details>

hmm Vector3 is a very general use in SE3, not necessary to be only used for translation. 
Here `repeated Vector3 way_points = 1;` and `repeated Vector3 stop_point;` also looks fine with me.

But if you think separating them is much better, I'm ok. I understand `Point3D` is for better meaning.


<!-- Sent from Reviewable.io -->

2022-01-23 19:53 UTC, ChaoFang-TRI reviewed
@chrisochoatri 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-Mu7SX5cCZWBWMWFKOpW:b1ogeqn)* status: 6 of 7 files reviewed, 18 unresolved discussions (waiting on @kuanleetri and @quincy-kh-chen)

___
*[dgp/proto/geometry.proto, line 9 at r2](https://reviewable.io/reviews/tri-ml/dgp/70#-Mr00Jqw4ej9M1c4WY0-:-Mu7On25C2y10LMeJvWT:buf5qo4) ([raw file](https://github.com/tri-ml/dgp/blob/3ace99dae0b20614d89b2e1ee1572b1b0de8eeef/dgp/proto/geometry.proto#L9)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

hmm Vector3 is a very general use in SE3, not necessary to be only used for translation. 
Here `repeated Vector3 way_points = 1;` and `repeated Vector3 stop_point;` also looks fine with me.

But if you think separating them is much better, I'm ok. I understand `Point3D` is for better meaning.
</blockquote></details>

I would prefer to keep Point3D a separate message of Vector3D
___
*[dgp/proto/map.proto, line 14 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpakZ94t6_5slYmBSP:-Mt4nQknBC6xTuORsRKX:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L14)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

no strong opinions here, but it could be argued all of these messages: lanes, lane dividers etc should/could be implemented as annotations that re use our existing geometric primitives and annotations.
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-Mt4nSW_7T4Z-14nSFvZ:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW what's the difference between `UNKNOWN` and `None`? Shall we just collapse these 2 categories into `UNKNOWN`?
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 88 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpdm-5AqwVZCKevjt-:-Mt4qnSK63k35IZgf0Ay:bkfiltx) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L88)):*
> google.protobuf.Any map_data = 4
done
___
*[dgp/proto/map.proto, line 98 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpdvUb20c_0mFCUoVG:-Mu7UvBiB2of7jWtkPMP:bb7f2mf) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L98)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW we can elaborate this as `Earth-centered Earth-fixed coordinate`
</blockquote></details>

done
___
*[dgp/proto/map.proto, line 42 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaYYsJAGMhT2T7g2Mq:-Mt4pymS-6NXwiBJUJGJ:b-yk8vbf) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L42)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Suggest renaming `UNCLEAR` to `UNKNOWN` for consistency.
</blockquote></details>

updated. Due to scoping issue, need to add prefix.
___
*[dgp/proto/map.proto, line 46 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaYwIa-Mo0qmCmWQ0L:-Mt4q6W1BBSQ5PIpyWrv:bb7f2mf) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L46)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW let's just the original message name `LaneDivider`
</blockquote></details>

done
___
*[dgp/proto/map.proto, line 47 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaZC2y2JMRJUVGtBCJ:-Mt4qEry-m-oVVlDTxcD:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L47)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

`type` for simplicity?
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 50 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaZEdlCqoV3pjXIjpA:-Mt4qJDnDEnFDGeJ0cq3:bb7f2mf) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L50)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

`color` for simplicity?
</blockquote></details>

done
___
*[dgp/proto/map.proto, line 52 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaZAXsEVmN-2oDBBXj:-Mt4qKJ08u0__QCvFBRE:bb7f2mf) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L52)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW let's just the original message name `LaneDivider`
</blockquote></details>

done
___
*[dgp/proto/map.proto, line 53 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaZKc41_uFGPbH_55D:-Mt4qLKh8s5OHUVe0Gf0:bb7f2mf) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L53)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

`material` for simplicity?
</blockquote></details>

done
___
*[dgp/proto/map.proto, line 61 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-Msa__O77rZWhoh8W_9Q:-Mt4qZnx0TNqTkv0uEcU:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L61)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Not a list? Isn't this just a single centerline?
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 102 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaaPdW1b2ql7i3GOQQ:-Mu7PHDz7otZuQ-VQL20:b-jc01zg) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L102)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW do we need to introduce the concept of `roadway`? i.e. a `roadway` consists of multiple `lane` in the same direction. 
</blockquote></details>

Currently, it is not used in any model.
___
*[dgp/proto/map.proto, line 121 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsabARLD--LjdzsgeUS:-Mu7PebO2JWsqbAhxjb7:b-2ya5ru) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L121)):*
> Earth-centered Earth-fixed coordinate system
done
___
*[dgp/proto/map.proto, line 22 at r4](https://reviewable.io/reviews/tri-ml/dgp/70#-MtQ0Lol5DBFYWVfI7jT:-Mu7PCkzACmJUjE5lGxa:bb7f2mf) ([raw file](https://github.com/tri-ml/dgp/blob/81428bcef88f88e76db7a6aaa9e9e7de70057acf/dgp/proto/map.proto#L22)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

typo: YPE -> TYPE
</blockquote></details>

done
___
*[dgp/proto/sample.proto, line 37 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpf1SE2vQczlog1D5i:-Mu7Q6xI70nUagvjv8-J:b-wimkao) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/sample.proto#L37)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

I agree with Quincy here. I think also map should be a datum, and all of these things like lanes, dividers, stop signs etc should be annotations. Someone literally has to annotate a map to get them. 
</blockquote></details>

@kuanleetri TrafficLightState is dynamic , that is the reason it is put in sample here but not in map. It is not a good idea to put map in a datum since datum values change time to time. It would waste many memory to put map in datum.


<!-- Sent from Reviewable.io -->

2022-01-24 20:42 UTC, ChaoFang-TRI reviewed
![Screenshot from 2022-01-24 12-42-33.png](https://files.reviewableusercontent.io/images/reviewable/58752910/zPz-UG3-dxhbNoqXR4dQMJVC/Screenshot%20from%202022-01-24%2012-42-33.png)

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MuCoiwM7ScqgNDA_xob:b-vfwb6s)* status: 3 of 7 files reviewed, 18 unresolved discussions (waiting on @kuanleetri and @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2022-01-24 21:54 UTC, chrisochoatri reviewed
thanks @chaofang-tri, I won't block this over the map as datum disagreement. I still think it would be good to get feedback from someone who intends to use this data or has more knowledge of the use cases. Otherwise this <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MuD3hud0I12T0wifC-u:b-wkkfte)* status: 3 of 7 files reviewed, 18 unresolved discussions (waiting on @kuanleetri and @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2022-01-24 23:13 UTC, quincy-kh-chen requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: all files reviewed, 12 unresolved discussions (waiting on @ChaoFang-TRI, @kuanleetri, and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-MuDJbnU9JNtr5sh79L2:b-l6vmyj) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We still have both `TYPE_UNKNOWN` and `TYPE_NONE`. Shall we just collapse them into `TYPE_UNKNOWN`? What's the difference?
___
*[dgp/proto/map.proto, line 123 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpeP0l-OER1gkTYRL_:-MuDLHX96WM6dVghyt8r:b7qbyyv) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L123)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

yes
</blockquote></details>

In some cases, a single TL controls multiple lanes. Should we make this field repeated?
___
*[dgp/proto/map.proto, line 132 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpea_pCezBTk7LNB64:-MuDLbmSCnVSGgjPa4n8:b2d1vz1) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L132)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

TL state are not static, it change over time
</blockquote></details>

Should we create an abstract wrapper `TrafficSignal` and a derived `TrafficLight` message that contains a repeated field `State` that encapsulates `state`, `timestamp_start`, and `timestamp_end`?
___
*[dgp/proto/map.proto, line 42 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaYYsJAGMhT2T7g2Mq:-MuDJzO_3kEhiXop-WYF:b-9o7cnx) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L42)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

updated. Due to scoping issue, need to add prefix.
</blockquote></details>

IMHO I don't think we need the prefix. Any reason why we are adding prefixes for all attributes?
___
*[dgp/proto/map.proto, line 101 at r5](https://reviewable.io/reviews/tri-ml/dgp/70#-MuDKU5y5CnRAPxMRpQB:-MuDKU5y5CnRAPxMRpQC:b8f1h1z) ([raw file](https://github.com/tri-ml/dgp/blob/f9d6f32f08ce1ea35d1a0ff91f98d0a66b200981/dgp/proto/map.proto#L101)):*
> ```protobuf
> // Represents a map -- either discrete segments or a pointer to an external data object (e.g. for rasterized maps).
> message SceneMap {
>   // List of Lanes in the map.
> ```

NIT: /map/SceneMap/
___
*[dgp/proto/map.proto, line 125 at r5](https://reviewable.io/reviews/tri-ml/dgp/70#-MuDKrHJBCLY3516IgF0:-MuDKrHJBCLY3516IgF1:b35c59r) ([raw file](https://github.com/tri-ml/dgp/blob/f9d6f32f08ce1ea35d1a0ff91f98d0a66b200981/dgp/proto/map.proto#L125)):*
> ```protobuf
> message DGPMap {
>   // List transformations from earth coord to vehicle coord.
>   repeated  LocalEarthTransform transforms = 1;
> ```

Can we just move `transforms` into `SceneMap` so that this additional wrapper `DGPMap` is unncessary?



_Code quote:_
```protobuf
repeated  LocalEarthTransform transforms = 1;
```


<!-- Sent from Reviewable.io -->

2022-01-24 23:47 UTC, kuanleetri reviewed
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: all files reviewed, 11 unresolved discussions (waiting on @ChaoFang-TRI and @quincy-kh-chen)

___
*[dgp/proto/sample.proto, line 37 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpf1SE2vQczlog1D5i:-MuDIdDL6MKirfyaZoOt:b-pbrwgs) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/sample.proto#L37)):*
<details><summary><i>Previously, ChaoFang-TRI (Chao Fang) wrote…</i></summary><blockquote>

@kuanleetri TrafficLightState is dynamic , that is the reason it is put in sample here but not in map. It is not a good idea to put map in a datum since datum values change time to time. It would waste many memory to put map in datum.
</blockquote></details>

I see, but I think what Quincy says is right. Do you think it's possible to try what Chris suggest?


<!-- Sent from Reviewable.io -->

2022-01-25 18:14 UTC, ChaoFang-TRI reviewed
> contrib folder 
@quincy-kh-chen @kuanleetri I realize traffic signal is very complicated and deserve a dedicated PR to handle. This PR only contains static part of the map.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MuHRAUa-FSHeRQcGb3H:bxzx0mz)* status: 3 of 7 files reviewed, 10 unresolved discussions (waiting on @ChaoFang-TRI, @kuanleetri, and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 26 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpbOT14HMt9f_jh2DM:-MuHIoqV6I6_5xvtGWgk:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L26)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

We still have both `TYPE_UNKNOWN` and `TYPE_NONE`. Shall we just collapse them into `TYPE_UNKNOWN`? What's the difference?
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 123 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-MqpeP0l-OER1gkTYRL_:-MuHJvGW1L-S8oD1RIiv:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L123)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

In some cases, a single TL controls multiple lanes. Should we make this field repeated?
</blockquote></details>

Done.
___
*[dgp/proto/map.proto, line 42 at r3](https://reviewable.io/reviews/tri-ml/dgp/70#-MsaYYsJAGMhT2T7g2Mq:-MuHITNA33hHj9eDUHb9:b8anjzi) ([raw file](https://github.com/tri-ml/dgp/blob/87b5199fe4e00c63ebc48448f203dc99aee6c6d3/dgp/proto/map.proto#L42)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

IMHO I don't think we need the prefix. Any reason why we are adding prefixes for all attributes?
</blockquote></details>

proto message has no scope, there would be namespace collision without prefix
___
*[dgp/proto/map.proto, line 125 at r5](https://reviewable.io/reviews/tri-ml/dgp/70#-MuDKrHJBCLY3516IgF0:-MuHIxq75psBZSjMv3Ca:bpx1ec7) ([raw file](https://github.com/tri-ml/dgp/blob/f9d6f32f08ce1ea35d1a0ff91f98d0a66b200981/dgp/proto/map.proto#L125)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Can we just move `transforms` into `SceneMap` so that this additional wrapper `DGPMap` is unncessary?
</blockquote></details>

OK, done


<!-- Sent from Reviewable.io -->

2022-01-26 04:51 UTC, ChaoFang-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: 3 of 7 files reviewed, 10 unresolved discussions (waiting on @kuanleetri and @quincy-kh-chen)

___
*[dgp/proto/map.proto, line 132 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpea_pCezBTk7LNB64:-MuJiBZf7w4EawW65yP8:b-552i5r) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/map.proto#L132)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Should we create an abstract wrapper `TrafficSignal` and a derived `TrafficLight` message that contains a repeated field `State` that encapsulates `state`, `timestamp_start`, and `timestamp_end`?
</blockquote></details>

removed tl from this PR
___
*[dgp/proto/sample.proto, line 37 at r1](https://reviewable.io/reviews/tri-ml/dgp/70#-Mqpf1SE2vQczlog1D5i:-MuJiFVw3BlgcWMKuydn:b-j92r8h) ([raw file](https://github.com/tri-ml/dgp/blob/4671744fd8d444aa19b27abd8098cc69973acc6d/dgp/proto/sample.proto#L37)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

I see, but I think what Quincy says is right. Do you think it's possible to try what Chris suggest?
</blockquote></details>

remove tl from this PR


<!-- Sent from Reviewable.io -->

2022-01-26 18:50 UTC, kuanleetri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MuMiTqNAbhSyGdApM1T:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2022-01-26 21:15 UTC, ChaoFang-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MuNEWh54xa0BShsxmIG:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2022-01-26 21:58 UTC, quincy-kh-chen reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MuNOKb04ohAe1al6YeC:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-26 22:36 UTC, quincy-kh-chen approved these changes
> Reviewed 2 of 4 files at r2, 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-26 22:36 UTC, kuanleetri approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-27 00:19 UTC, ChaoFang-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MuNtjrP15SUyUte3iWC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-27 00:20 UTC, ChaoFang-TRI reviewed
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-27 00:21 UTC, ChaoFang-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MuNtz6C3M7mDFyl-0M1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-27 00:21 UTC, ChaoFang-TRI reviewed
-@chrisochoatri 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70#-:-MuNuDk6DeTlj1k2II0M:b-d9qetg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-27 00:22 UTC, ChaoFang-TRI reviewed
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-27 00:43 UTC, kuanleetri approved these changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-27 18:38 UTC, chrisochoatri approved these changes
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChaoFang-TRI)



<!-- Sent from Reviewable.io -->

2022-01-27 18:39 UTC, merged