schema: add support for additional camera models in camera intrinsics
TRI-ML/dgp pull request #86
Opened 2022-04-15 20:46 UTC by chrisochoatri

This updates the camera intrinsics proto to include the changes made by PD: https://github.com/parallel-domain/dgp/blob/master/dgp/proto/geometry.proto#L30 
But also adds support for other camera distortion models such as the double sphere model.

Additional PRs will be needed for the dataloaders to use this information.

2022-04-19 17:15 UTC, pkarasev3 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86#-:-N01oWAZ8YYUj7dElDGF:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @pkarasev3)

___
*[dgp/proto/geometry.proto, line 51 at r1](https://reviewable.io/reviews/tri-ml/dgp/86#-N01nypt2mtHc2PjNkxM:-N01nypu9xGYUlVA8V2Z:bjij51m) ([raw file](https://github.com/tri-ml/dgp/blob/37b1d1fbc8f7b7214fb95eb2f204f7da2dc9b941/dgp/proto/geometry.proto#L51)):*
> ```protobuf
>   double fov = 6;
>   int32  fisheye = 7;
>   double k1 = 8;
> ```

consider grouping these into a struct to separate from other optional groups
___
*[dgp/proto/geometry.proto, line 78 at r1](https://reviewable.io/reviews/tri-ml/dgp/86#-N01o6jYEuJoKNkL8C5D:-N01o6jYEuJoKNkL8C5E:b-dpd252) ([raw file](https://github.com/tri-ml/dgp/blob/37b1d1fbc8f7b7214fb95eb2f204f7da2dc9b941/dgp/proto/geometry.proto#L78)):*
> ```protobuf
> 
>   // Parameters for Double Sphere model
>   double xi = 25;
> ```

Aren't some of these groups exclusive? consider using the 'oneof' declaration of proto if so.


<!-- Sent from Reviewable.io -->

2022-04-19 19:46 UTC, chrisochoatri reviewed
Thanks Peter, any thoughts/comments @quincy-kh-chen @kuanleetri @chaofang-tri @visakii-work  ?

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86#-:-N02LwA467mkCsCyiaxO:bvepeft)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @pkarasev3)



<!-- Sent from Reviewable.io -->

2022-04-19 19:52 UTC, chrisochoatri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @pkarasev3)

___
*[dgp/proto/geometry.proto, line 51 at r1](https://reviewable.io/reviews/tri-ml/dgp/86#-N01nypt2mtHc2PjNkxM:-N02NYF5CbhojIBAAOOr:b-6n2ys6) ([raw file](https://github.com/tri-ml/dgp/blob/37b1d1fbc8f7b7214fb95eb2f204f7da2dc9b941/dgp/proto/geometry.proto#L51)):*
<details><summary><i>Previously, pkarasev3 (peter karasev) wrote…</i></summary><blockquote>

consider grouping these into a struct to separate from other optional groups
</blockquote></details>

I completely agree, but I was trying to be backward compatible with the PD version.


<!-- Sent from Reviewable.io -->

2022-04-19 20:58 UTC, kuanleetri requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86)* status: all files reviewed, 3 unresolved discussions (waiting on @chrisochoatri and @pkarasev3)

___
*[dgp/proto/geometry.proto, line 95 at r1](https://reviewable.io/reviews/tri-ml/dgp/86#-N02bRZO9VOaY_weyfNG:-N02bRZP6BXqLxs5FaCZ:b-sahsrj) ([raw file](https://github.com/tri-ml/dgp/blob/37b1d1fbc8f7b7214fb95eb2f204f7da2dc9b941/dgp/proto/geometry.proto#L95)):*
> ```protobuf
>   }
> 
>   CameraModel model = 26;
> ```

is by default PINHOLE?



_Code quote:_
```protobuf
PINHOLE
```


<!-- Sent from Reviewable.io -->

2022-04-20 16:31 UTC, quincy-kh-chen requested changes
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86)* status: all files reviewed, 4 unresolved discussions (waiting on @chrisochoatri and @pkarasev3)

___
*[dgp/proto/geometry.proto, line 81 at r1](https://reviewable.io/reviews/tri-ml/dgp/86#-N06o5YM-89_gUKYhwdN:-N06o5YM-89_gUKYhwdO:b-y0s1ph) ([raw file](https://github.com/tri-ml/dgp/blob/37b1d1fbc8f7b7214fb95eb2f204f7da2dc9b941/dgp/proto/geometry.proto#L81)):*
> ```protobuf
> 
>   enum CameraModel {
>     UNDEFINED =0;
> ```

Suggest renaming to `UNKNOWN` to be consistent with dgp convention.


<!-- Sent from Reviewable.io -->

2022-04-21 16:40 UTC, chrisochoatri reviewed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @kuanleetri, @pkarasev3, and @quincy-kh-chen)

___
*[dgp/proto/geometry.proto, line 78 at r1](https://reviewable.io/reviews/tri-ml/dgp/86#-N01o6jYEuJoKNkL8C5D:-N0BzZVJ6tSUE7sEjTDl:btrbwuy) ([raw file](https://github.com/tri-ml/dgp/blob/37b1d1fbc8f7b7214fb95eb2f204f7da2dc9b941/dgp/proto/geometry.proto#L78)):*
<details><summary><i>Previously, pkarasev3 (peter karasev) wrote…</i></summary><blockquote>

Aren't some of these groups exclusive? consider using the 'oneof' declaration of proto if so.
</blockquote></details>

I removed the enum, need to think about this a little bit more. For now we will have to just know what model we expect to apply for each camera.
___
*[dgp/proto/geometry.proto, line 81 at r1](https://reviewable.io/reviews/tri-ml/dgp/86#-N06o5YM-89_gUKYhwdN:-N0Bziow0KbE0zHIIQ_6:b9xvtei) ([raw file](https://github.com/tri-ml/dgp/blob/37b1d1fbc8f7b7214fb95eb2f204f7da2dc9b941/dgp/proto/geometry.proto#L81)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Suggest renaming to `UNKNOWN` to be consistent with dgp convention.
</blockquote></details>

removed for now
___
*[dgp/proto/geometry.proto, line 87 at r1](https://reviewable.io/reviews/tri-ml/dgp/86#-N06oGlMBeRPshFnp7u8:-N0BzjlC1sjD7pdJP4Ok:b9xvtei) ([raw file](https://github.com/tri-ml/dgp/blob/37b1d1fbc8f7b7214fb95eb2f204f7da2dc9b941/dgp/proto/geometry.proto#L87)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW uppercase for consistency
</blockquote></details>

removed for now
___
*[dgp/proto/geometry.proto, line 95 at r1](https://reviewable.io/reviews/tri-ml/dgp/86#-N02bRZO9VOaY_weyfNG:-N0Bzhsp-y65Iow6ViVU:b9xvtei) ([raw file](https://github.com/tri-ml/dgp/blob/37b1d1fbc8f7b7214fb95eb2f204f7da2dc9b941/dgp/proto/geometry.proto#L95)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

is by default PINHOLE?
</blockquote></details>

removed for now


<!-- Sent from Reviewable.io -->

2022-04-22 00:54 UTC, kuanleetri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86#-:-N0Dks9j6ICKlJfh6Il6:bnfp4nl)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @kuanleetri, @pkarasev3, and @quincy-kh-chen)



<!-- Sent from Reviewable.io -->

2022-04-22 00:56 UTC, quincy-kh-chen reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86#-:-N0DlGe66gDJefDnIQIv:bg7igkv)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @kuanleetri and @pkarasev3)



<!-- Sent from Reviewable.io -->

2022-04-22 02:06 UTC, chrisochoatri reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86)* status: all files reviewed, 2 unresolved discussions (waiting on @pkarasev3)



<!-- Sent from Reviewable.io -->

2022-04-22 02:14 UTC, kuanleetri submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86)* status: all files reviewed, 2 unresolved discussions (waiting on @pkarasev3)



<!-- Sent from Reviewable.io -->

2022-04-22 04:59 UTC, quincy-kh-chen approved these changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/86)* status: all files reviewed, 2 unresolved discussions (waiting on @pkarasev3)



<!-- Sent from Reviewable.io -->

2022-06-29 04:43 UTC, wadimkehl commented
Is there any movement on this? Would be good for our use cases, too! @kuanleetri

2022-06-30 00:18 UTC, merged